### DISCUSSION TITLE
Akvorado UI Not display Graph and have error SNMP

### DISCUSSION THREAD

**Discussion by alifgufron** [akvorado/akvorado#1154] [Q&A] [answered]
Hello everyone,

im have same problem when using akvorado data not display but show only last flow recived.

```
# curl -s http://127.0.0.1:8080/api/v0/inlet/metrics | grep '^akvorado_inlet_flow_input_udp_packets'
akvorado_inlet_flow_input_udp_packets_total{exporter="192.168.1.1",listener=":2055",worker="0"} 3
akvorado_inlet_flow_input_udp_packets_total{exporter="192.168.1.1",listener=":2055",worker="1"} 608860

# curl -s http://127.0.0.1:8080/api/v0/inlet/metrics | grep '^akvorado_inlet' | grep _errors
akvorado_inlet_core_flows_errors_total{error="SNMP cache miss",exporter="192.168.1.1.1"} 285
akvorado_inlet_flow_decoder_errors_total{name="netflow"} 363
akvorado_inlet_flow_decoder_netflow_errors_total{error="NetFlow/IPFIX decoding error",exporter="192.168.1.1"} 363
```

on akvorado.yaml asns set to my isp and on inlet.yaml set ip and comunity but still not display data

```
metadata:
  workers: 10
  provider:
    type: snmp
    communities:
      #::/0: public
      192.168.1.1: kucinG
flow:
  inputs:
    - type: udp
      decoder: netflow
      listen: 2055
      workers: 6
      use-src-addr-for-exporter-addr: true
      receive-buffer: 10485760
    - type: udp
      decoder: sflow
      listen: :6343
      workers: 6
      receive-buffer: 10485760
core:
  override-sampling-rate: 10
  workers: 6
  exporter-classifiers:
    - ClassifySiteRegex(Exporter.Name, "^[^-]+-([^-]+)-", "$1")
    - ClassifyRegionRegex(Exporter.Name, "^([^-])+-[^-]+-", "$1")
    #- ClassifyTenant("AS9657")
    #- ClassifyRole("melsa")
  interface-classifiers:
    - |
      ClassifyConnectivityRegex(Interface.Description, "^(?i)(transit|peering):? ", "$1") &&
      ClassifyProviderRegex(Interface.Description, "^\\S+?\\s(?:to )?(\\S+)", "$1") &&
      ClassifyExternal()
    - ClassifyConnectivityRegex(Interface.Description, "^(?i)(cust|core):? ", "$1") &&
      ClassifyInternal()
    - ClassifyInternal()
```

anyone can help me im try reinstall and configure but still error,

Thank
