### DISCUSSION TITLE
Problem with console customization - the example on the documentation is broken

### DISCUSSION THREAD

**Discussion by sgaragna** [akvorado/akvorado#1183] [Q&A]
We have deployed a 1.10.1 version, on Debian Linux Sysyem, Docker version 26.0.1 and docker compose 2.26.1
We want to customize the homepage-top-widgets and default-visualize-options:
If we try with the documentation example, the docker compose fail with a container in starting loop.

The same if i try with our customized console.yml

The error on the retrieved logs is:
```
Error: invalid configuration:
invalid key "Console[0].console"

```
The console.yml configured is:
```

http:
  cache:
    type: redis
    server: redis:6379
database:
  saved-filters:
    # These are prepopulated filters you can select in a drop-down
    # menu. Users can add more filters interactively.
#    - description: "From Netflix"
#      content: >-
#        InIfBoundary = external AND SrcAS = AS2906
    - description: "To ENEGAN"
      content: DstAS = 208808
#        InIfBoundary = external AND
#        DstAS = 208808
console:
  homepage-top-widgets: [src-as, src-country, exporter, protocol, etype, src-port]
  default-visualize-options:
    start: 1 day ago
    end: now
    filter: DstAS = 208808
    dimensions:
      - SrcAS
  homepage-graph-filter:


```
Can anybody explain where is the errors???
Thank you very much.
