### DISCUSSION TITLE
snmpv3 configutation

### DISCUSSION THREAD

**Discussion by geekev** [akvorado/akvorado#1196] [Q&A] [answered]
Hi,
I'm looking for some help with our SNMPv3 config. I'm running the akvorado binary on Debian 10 (buster). I can see authentication errors in my Juniper network device logs .
I've tried lots of different permutations based on a few examples I've found online and in these discussions.
Questions I have that may or may not be irrelevant.
- Do I need to set `::/0` (I have tried this)?
-  is the `type` key correct as per example in the documentation? 
- is `providers` correct rather than `provider` as in `ERR akvorado/inlet/metadata/provider/snmp/poller.go:115 > unable to GET `
- If I change my `config.yaml` is it sufficient to re-run `./akvorado inlet http://localhost:8081` or do I need to restart `akvorado_orchestrator`?

Extract from my config:
```
inlet:
…
  metadata:
    workers: 10
    providers:
      type: snmp
      security-parameters:
        user-name: snmpuser
        authentication-protocol: SHA
        authentication-passphrase: #############
        privacy-protocol: AES
        privacy-passphrase: ##############
```

I've also tried:
```
  metadata:
    workers: 10
    providers:
      type: snmp
      security-parameters:
        10.0.0.0/8:
          user-name: snmpuser
          authentication-protocol: SHA
          authentication-passphrase: #############
          privacy-protocol: AES
          privacy-passphrase: ##############
```

Any help gratefully received.
Kevin
