### DISCUSSION TITLE
console - Error: received configuration file is not YAML

### DISCUSSION THREAD

**Discussion by geekev** [akvorado/akvorado#1209] [Q&A]
Hi Vincent,

Sorry to bother you again, can you help me with this please? I think I am close to getting everything working.

I am running this:

`./akvorado console http://localhost:8080`

And I get:
`Error: received configuration file is not YAML (text/plain)`

Redacted config file below (I only added the `---` because I got the error, it makes no difference.

```
--- #Added to try and cure YAML error
http:
  listen: 127.0.0.1:8081
kafka:
  topic: netflow-topic
  brokers:
    - localhost:9092
clickhouse:
  password: XXXXXXXXXXXXXX
inlet:
  flow:
    inputs:
      - type: udp
        decoder: netflow
        listen: 0.0.0.0:2055
        workers: 3
        use-src-addr-for-exporter-addr: true
      - type: udp
        decoder: sflow
        listen: 0.0.0.0:6343
        workers: 3
  metadata:
    workers: 10
    providers:
      type: snmp
      security-parameters:
        10.0.0.0/8:
          user-name: SNMPUSER
          authentication-protocol: SHA
          authentication-passphrase: XXXXXXXXXXXXXXXX
          privacy-protocol: AES
          privacy-passphrase: XXXXXXXXXXX
```
