### DISCUSSION TITLE
Use cloud clickhouse for storage

### DISCUSSION THREAD

**Discussion by mmarin11** [akvorado/akvorado#1236] [Q&A]
Hi akvorado community. We are planning to deploy akvorado for flow analysis and storage purposes and I was wondering if using a cloud base clickhouse instance instead of on premise one is an option. Basically deploy the flow collector on premise and the flow collector will push data to the clickhouse cloud instance.

**Comment by vincentbernat** [comment]
I think there are a few differences on how ReplicatedMergeTree are handled. It may not work out of the box. I don't think it would be hard to adapt but it may need some code adaptation.

**Comment by vincentbernat** [comment]
After reading https://clickhouse.com/docs/en/whats-new/cloud-compatibility, I see it cannot work as Kafka engine is not supported in ClickHouse cloud. Other than that, it should work out of the box:

```yaml
clickhouse:
 servers:
  - xxxxxx.clickhouse.cloud:9440
 username: default
 password: "..."
 tls:
  enable: true
 orchestrator-url: http://public.ip.for.orchestrator
```

The latest configuration is needed for ClickHouse to be able to fetch the dictionaries.
