### DISCUSSION TITLE
How to remove default filter ?

### DISCUSSION THREAD

**Discussion by nneo16** [akvorado/akvorado#1248] [Q&A] [answered]
Example my console.yaml

```
default-visualize-options:
         start: 6 hours ago
         end: now
         filter:
```
Tried but it stills get the default filter.
Tried filter: [] > service 404.
