### DISCUSSION TITLE
Missing Interfaces / Interface mismatches

### DISCUSSION THREAD

**Discussion by T1MB00** [akvorado/akvorado#1275] [Q&A]
Hi, we have been using Akvorado for flow collection from Nokia routers for a few days now. 
Currently, we are facing an issue that some interfaces are not displayed in Akvorado OR they do not have (correct) interface names/descriptions. However, this does not affect all interfaces, only a few interfaces across all routers. 
It is also possible (most likely) that the assignment of interfaces is simply incorrect.

Concrete example:

- My Nokia router has an interface "PROVIDER01" with the description: "Transit: PROVIDER01 [10Gbps] (UNKNOWN)"
- cflowd collection is active on the interface
- The router sends traffic over the interface to the following gateway 'XXX.XXX.XXX.YYY'
- No Interface named "PROVIDER01" with the description: "Transit: PROVIDER01 [10Gbps] (UNKNOWN)" is shown up. But there are generally existing interfaces with names and descriptions.

Now, if I display the flows coming into Akvorado and filter by the next-hop address, I see corresponding flows for this interface:
`curl --insecure https://127.0.0.1/api/v0/inlet/flows | grep 'XXX.XXX.XXX.YYY'`

Output Example:
`{"TimeReceived":1718754460,"SamplingRate":1,"ExporterAddress":"AAA.AAA.AAA.AAA","InIf":0,"OutIf":18,"SrcVlan":0,"DstVlan":0,"SrcAddr":"BBB.BBB.BBB.BBB","DstAddr":"CCC.CCC.CCC.CCC","NextHop":"XXX.XXX.XXX.YYY","SrcAS":12345,"DstAS":54321,"GotASPath":false,"SrcNetMask":EE,"DstNetMask":FF}`

When I then filter in the Akvorado web interface by the corresponding parameters (ExporterAddress, SrcAddr, DstAddr, etc.), I get interface names and descriptions that do not match the actual router interface. Therefore, my assumption is that the interfaces (ID to Names/Descriptions) are not correctly assigned.

At what point or how can I view and possibly correct the assignment of the interfaces?
What other troubleshooting options do I have?

**Comment by vincentbernat** [comment]
Can you check with SNMP what do you get for IfDescription.18 and 
IfAlias.18 on this device?

**Reply by T1MB00** [reply]
snmpwalk shows me interface 18 with the name "CUSTOMERXYZ" and no description (which basically matches the interface) but definitely cannot be the interface corresponding to the flow mentioned above.
The expected interface "PROVIDER01" with the description: "Transit: PROVIDER01 [10Gbps] (UNKNOWN)" is shown to me with ID 11.

**Reply by vincentbernat** [reply]
So, it seems there is an issue with the flow sent by your Nokia. You could confirm with a capture the index, but it seems unlikely that Akvorado changes it. Maybe you can raise this issue to Nokia support. There are also some Nokia people lurking here, maybe they know what could be the problem.

**Reply by rinsekloek** [reply]
I had the same issue, but it appears that if you use the default Nokia config, the In/Out interfaces is not the IfIndex from SNMP or GNMIC. Either you have to set the global setting to :
  `"cflowd use-vrtr-if-index     - Export flow data using virtual router interface indexes"`
 
Or use a custom model in gnmic. This is my config. It's the system-if-index that contains the right value.
The only thing I need to check is the Interface speed, that's not the correct value I guess.

This is the config under metadata -> provider

```
    models:
        - name: NokiaSROSSystem
          ifindexpaths:
            - /state/router/interface/system-if-index
          ifdescriptionpaths:
            - /configure/router/interface/description
          ifnamekeys: [interface-name]
          ifnamepaths:
            - /state/router/interface/interface-name
          ifspeedpaths:
            - path: /state/lag/bandwidth
              unit: mbps
          systemnamepaths:
            - /configure/system/name
```

**Reply by vincentbernat** [reply]
This could be used as the default configuration if you can confirm it works for both regular interface and lags.

**Reply by rinsekloek** [reply]
I can confirm this works for lags, however did not test it for regular interfaces, need to check this

Only the ifspeedpaths, I can not define it correctly as we have a seperate key for that.
[lag-name=lag-BE11507] in this case

```
gnmic -a <left out host/user/pass> --path  '/state/lag/bandwidth/' 
    {
        "Path": "state/lag[lag-name=lag-BE11507]/bandwidth",
        "values": {
          "state/lag/bandwidth": "800000000"
        }
      },

This is the method to get these key (by interface-name)
gnmic -a <left out host/user/pass> --path '/configure/router/interface/port'

{
        "Path": "configure/router[router-name=Base]/interface[interface-name=BE11507]/port",
        "values": {
          "configure/router/interface/port": "lag-BE11507"
        }
      },


```

**Comment by zxyz** [comment]
My current approach including IES interfaces is:

```
    models:
      - name: custom
        if-index-paths:
          - /state/router/interface/system-if-index
          - /state/service/ies/interface/system-if-index
        if-description-paths:
          - /configure/router/interface/description
          - /configure/service/ies/interface/description
        #if-name-keys: [interface-name]
        if-name-paths:
          - /state/router/interface/interface-name
          - /state/service/ies/interface/interface-name
        if-speed-paths:
          - path: /state/lag/bandwidth
            unit: bps
          - path: /state/port/ethernet/oper-speed
            unit: mbps
        system-name-paths: /configure/system/name
```

ifspeed as well not working and still not all interfaces classified (trying to hunt them down looking at the current flow on the akvorado start page, waiting for a partially unclassified flow to show up and then follow the src and dst interfaces to figure out the interfaces, any better approaches anyone?), but maybe it already helps someone.

classification works for regular interfaces as well.
