### DISCUSSION TITLE
Wrong traffic graphs to the correct ASN

### DISCUSSION THREAD

**Discussion by LeuciJP** [akvorado/akvorado#1332] [Q&A] [answered]
Hello,
I've been trying to set up akvorado for a while now, which is a really useful tool, thanks for this usefulness!

We would like to use akvorado, but the statistics do not seem to be correct, the outgoing traffic differs considerably from the reality (outgoing traffic is over 300Gbit, but according to akvorado only 10Gbit).

The config looks like this, I suspect that this is the problem.
The ports are “Transit, Peering or Downstream”

```
core:
  workers: 1
  exporter-classifiers:
    # This is an example. This should be customized depending on how
    # your exporters are named.
    - ClassifySiteRegex(Exporter.Name, "^([^-]+)-", "$1")
  interface-classifiers:
    # This is an example. This must be customized depending on the
    # descriptions of your interfaces. In the following, we assume
    # external interfaces are named "Transit: Cogent" Or "IX:
    # FranceIX".
    - |
      ClassifyConnectivityRegex(Interface.Description, "^(?i)(transit|peering|downstream|ix):? ", "$1") &&
      ClassifyProviderRegex(Interface.Description, "^\\S+?\\s(\\S+)", "$1") &&
      ClassifyExternal()
    - ClassifyInternal()
```

In the akvorado.yaml file all networks are provided and the assigned ASN.

Am I missing something?

Thanks for all the help already!
