### DISCUSSION TITLE
After Upgrade - Services not starting

### DISCUSSION THREAD

**Discussion by cmurrayis** [akvorado/akvorado#139] [Q&A]
Hi,
I had Akvorado running for a couple of months since we last spoke and it has been good so I went to upgrade. I checked through the Changelogs and noted nothing special in the requirements so went ahead and updated via Docker-Compose. I restarted all containers and now it seems to be stuck in a loop with the following error in the orchestrator;

```
* '[::/0]' expected a map, got 'slice'
Error: unable to parse configuration: 1 error(s) decoding:

* error decoding 'ClickHouse.Networks': unable to decode "NetworkAttributes": 1 error(s) decoding:
```

**Comment by vincentbernat** [comment]
Do you mind sharing a bit what the "clickhouse.networks" section of your configuration looks like? Likely, you can workaround the issue by using the "map" format for the entries (name, group, role, etc). Look at the `akvorado.yaml` provided as an example. But if your configuration was working previously, it should be handled by the new versions nonetheless.

**Reply by cmurrayis** [reply]
Hi Vincent, Do you mind sharing the correct steps to upgrade as I have rolled back to an earlier snapshot. 

Once I have the correct steps I will try it again.

**Reply by vincentbernat** [reply]
Do not upgrade yet. Give me the snippet of configuration you have in `akvorado.yaml` in `clickhouse` → `networks`.

**Reply by cmurrayis** [reply]
Hi Vincent,

```
clickhouse:
  orchestrator-url: http://akvorado-orchestrator:8080
  kafka:
    consumers: 2
  servers:
    - clickhouse:9000
  asns:
    Our_ASN: Our_Company_Name
  networks:
    - 192.0.2.0/24: customers
    - 203.0.113.0/24: servers
    - 2a01:db8:cafe:1::/64: customers
    - 2a01:db8:cafe:2::/64: servers
```
The network section is still per the example - we have not modified as not sure what the use of this is.
