### DISCUSSION TITLE
Sampling rate not read from Fortinet FortiGate netflow

### DISCUSSION THREAD

**Discussion by joelmoxey** [akvorado/akvorado#1391] [Q&A]
I am looking at netflow from a FortiGate. I see sampling interval = 1 using template 257.

Akvorado reported it was missing on the inlet. Added a default of 20.

20 seems to be used. Please can you have a look at pcap and screenshot to advise if there is something up?

[pcap_screenshot.zip](https://github.com/user-attachments/files/16915219/pcap_screenshot.zip)

Thanks.

Joel

```
root@ubuntu-15-28:~/akvorado# docker compose exec akvorado-orchestrator akvorado orchestrator --check --dump /etc/akvorado/akvorado.yaml
---
reporting:
    logging: {}
    metrics: {}
http:
    listen: :8080
    profiler: true
    cache:
        type: memory
clickhouse:
    servers:
        - clickhouse:9000
    cluster: ""
    database: default
    username: default
    password: ""
    maxopenconns: 10
    dialtimeout: 5s
    tls:
        enable: false
        verify: true
        cafile: ""
        certfile: ""
        keyfile: ""
    skipmigrations: false
    kafka:
        topic: flows
        brokers:
            - kafka:9092
        version: 3.3.1
        tls:
            enable: false
            verify: true
            cafile: ""
            certfile: ""
            keyfile: ""
            saslusername: ""
            saslpassword: ""
            saslmechanism: none
        consumers: 4
        groupname: clickhouse
        enginesettings: []
    resolutions:
        - interval: 0s
          ttl: 360h0m0s
        - interval: 1m0s
          ttl: 168h0m0s
        - interval: 5m0s
          ttl: 2160h0m0s
        - interval: 1h0m0s
          ttl: 8640h0m0s
    maxpartitions: 50
    systemlogttl: 720h0m0s
    prometheusendpoint: /metrics
    asns:
        64501: ACME Corporation
    networks:
        2a01:db8:cafe:1::/64:
            name: ipv6-customers
            role: customers
            site: ""
            region: ""
            city: ""
            state: ""
            country: ""
            tenant: ""
            asn: 0
        2a01:db8:cafe:2::/64:
            name: ipv6-servers
            role: servers
            site: ""
            region: ""
            city: ""
            state: ""
            country: ""
            tenant: ""
            asn: 0
        192.0.2.0/24:
            name: ipv4-customers
            role: customers
            site: ""
            region: ""
            city: ""
            state: ""
            country: ""
            tenant: ""
            asn: 0
        203.0.113.0/24:
            name: ipv4-servers
            role: servers
            site: ""
            region: ""
            city: ""
            state: ""
            country: ""
            tenant: ""
            asn: 0
    networksources: {}
    networksourcestimeout: 10s
    orchestratorurl: http://akvorado-orchestrator:8080
kafka:
    topic: flows
    brokers:
        - kafka:9092
    version: 3.3.1
    tls:
        enable: false
        verify: true
        cafile: ""
        certfile: ""
        keyfile: ""
        saslusername: ""
        saslpassword: ""
        saslmechanism: none
    topicconfiguration:
        numpartitions: 8
        replicationfactor: 1
        configentries:
            cleanup.policy: delete
            compression.type: producer
            retention.ms: "86400000"
            segment.bytes: "1073741824"
        configentriesstrictsync: true
geoip:
    asndatabase:
        - /usr/share/GeoIP/asn.mmdb
    geodatabase:
        - /usr/share/GeoIP/country.mmdb
    optional: true
schema:
    disabled: []
    enabled: []
    maintableonly: []
    notmaintableonly: []
    materialize: []
    customdictionaries: {}
inlet:
    - reporting:
        logging: {}
        metrics: {}
      http:
        listen: :8080
        profiler: true
        cache:
            type: memory
      flow:
        inputs:
            - decoder: netflow
              listen: :2055
              queuesize: 100000
              receivebuffer: 10485760
              timestampsource: udp
              type: udp
              usesrcaddrforexporteraddr: false
              workers: 6
            - decoder: sflow
              listen: :6343
              queuesize: 100000
              receivebuffer: 10485760
              timestampsource: udp
              type: udp
              usesrcaddrforexporteraddr: false
              workers: 6
        ratelimit: 0
      metadata:
        cacheduration: 30m0s
        cacherefresh: 1h0m0s
        cachecheckinterval: 2m0s
        cachepersistfile: ""
        providers:
            - agents:
                212.183.148.10: 192.168.194.2
              communities:
                ::/0:
                    - zabbix
              pollerretries: 1
              pollertimeout: 1s
              ports:
                ::/0: 161
              securityparameters: {}
              type: snmp
        workers: 10
        maxbatchrequests: 10
      routing:
        provider:
            collectasns: true
            collectaspaths: true
            collectcommunities: true
            keep: 5m0s
            listen: :10179
            rds: []
            ribpeerremovalbatchroutes: 5000
            ribpeerremovalmaxqueue: 10000
            ribpeerremovalmaxtime: 100ms
            ribpeerremovalsleepinterval: 500ms
            type: bmp
      kafka:
        topic: flows
        brokers:
            - kafka:9092
        version: 3.3.1
        tls:
            enable: false
            verify: true
            cafile: ""
            certfile: ""
            keyfile: ""
            saslusername: ""
            saslpassword: ""
            saslmechanism: none
        flushinterval: 1s
        flushbytes: 104857599
        maxmessagebytes: 1000000
        compressioncodec: zstd
        queuesize: 32
      core:
        workers: 6
        exporterclassifiers:
            - ClassifySiteRegex(Exporter.Name, ".*", "$1")
            - ClassifyRegion("europe")
            - ClassifyTenant("acme")
            - ClassifyRole("edge")
        interfaceclassifiers:
            - |
              ClassifyConnectivityRegex(Interface.Description, ".*", "$1") &&
              ClassifyProviderRegex(Interface.Description, ".*", "$1") &&
              ClassifyExternal()
            - ClassifyInternal()
        classifiercacheduration: 5m0s
        defaultsamplingrate:
            ::/0: 20
        overridesamplingrate: {}
        asnproviders:
            - flow
            - routing
        netproviders:
            - flow
            - routing
      schema:
        disabled: []
        enabled: []
        maintableonly: []
        notmaintableonly: []
        materialize: []
        customdictionaries: {}
console:
    - reporting:
        logging: {}
        metrics: {}
      http:
        listen: :8080
        profiler: true
        cache:
            db: 0
            password: ""
            protocol: tcp
            server: redis:6379
            type: redis
            username: ""
      defaultvisualizeoptions:
        graphtype: stacked
        start: 6 hours ago
        end: now
        filter: InIfBoundary = external
        dimensions:
            - SrcAS
        limit: 10
        bidirectional: false
        previousperiod: false
      homepagetopwidgets:
        - src-as
        - src-port
        - protocol
        - src-country
        - etype
      homepagegraphfilter: InIfBoundary = 'external'
      homepagegraphtimerange: 24h0m0s
      dimensionslimit: 50
      cachettl: 3h0m0s
      clickhouse:
        servers:
            - clickhouse:9000
        cluster: ""
        database: default
        username: default
        password: ""
        maxopenconns: 10
        dialtimeout: 5s
        tls:
            enable: false
            verify: true
            cafile: ""
            certfile: ""
            keyfile: ""
      auth:
        headers:
            login: Remote-User
            name: Remote-Name
            email: Remote-Email
            logouturl: X-Logout-URL
        defaultuser:
            login: __default
            name: Default User
            email: ""
            logouturl: ""
      database:
        driver: sqlite
        dsn: file::memory:?cache=shared
        savedfilters:
            - description: From Netflix
              content: InIfBoundary = external AND SrcAS = AS2906
            - description: From GAFAM
              content: InIfBoundary = external AND SrcAS IN (AS15169, AS16509, AS32934, AS6185, AS8075)
      schema:
        disabled: []
        enabled: []
        maintableonly: []
        notmaintableonly: []
        materialize: []
        customdictionaries: {}
demoexporter: []
```
