### DISCUSSION TITLE
Can we change default netflow port 2055 with other port?

### DISCUSSION THREAD

**Discussion by kronicklez** [akvorado/akvorado#1422] [Q&A]
Hi all,

Currently i'm using docker method. Current testing the Juniper router from other place will send jflow9 to Akvorado in other place through internet. Means firewall in front of akvorado already do port forwarding 2055 and snmp 161 and 162. But the i'm not see any flow receive in akvorado. Reachability no issue between Router to akvorado and vice versa. Is it any port that i need to port forward instead netflow and snmp port? So i'm plan to change default port 2055 netflow to other port because to make sure it not issue ISP block port 2055. So appreciate if someone guide me which file that need to change and step.

Thanks and appreciate any advise.

**Comment by adjiekrazz** [comment]
Yes we can change the default netflow port.  We can found the listener configuration at inlet.yaml file.

```
flow:
  inputs:
    - type: udp
      decoder: netflow
      listen: :2055
      workers: 12
      receive-buffer: 20971520 # 20 MB
```
