### DISCUSSION TITLE
No Pie Chart Data

### DISCUSSION THREAD

**Discussion by dbray925** [akvorado/akvorado#1509] [Q&A] [answered]
I'm a little stumped on this issue. Everything appears to be working just fine. Can't really see an error in any of the logs, and all the API checks come back with expected results and gives only a few initial "SNMP cache miss" and "NetFlow v9 decoding error", but those numbers are not growing. Furthermore, the Visualize tab appears to be decoding everything properly. I see proper SrcAddr, SrcPort, SrcAS, DstAddr, DstPort, DstAS, etc. 

The only thing that I can't seem to figure out is why the Pie Graphs on the home page are all 100% "Others" data:
![image](https://github.com/user-attachments/assets/a386176c-673e-4f2f-8c41-b3ff60cd1554)
The line chart underneath is populating data as expected, and I'm seeing hundreds+ Flows/s, it's just the Pie Graphs "look blank". The config file is very basic without filters:
```
      homepage-top-widgets:
        - src-as
        - src-port
        - protocol
        - etype
      homepage-graph-filter: ''
```

**Comment by Atze2022** [comment]
I have the same grey graphs :-(

**Comment by vincentbernat** [comment, marked as answer]
The widgets rely on boundary being set correctly (`InIfBoundary = external` for source widgets, `OutIfBoundary = external` for all the others).

**Reply by dbray925** [reply]
Got it, thank you!

For us, I updated:

```
inlet:
      core:
        workers: 5
        exporter-classifiers:
          - ClassifySiteRegex(Exporter.Name, "^([^-]+)-", "$1")
          - ClassifyRegion("Home")
          - ClassifyTenant("LANDomain")
          - ClassifyRole("Router")
        interface-classifiers:
          - ClassifyConnectivityRegex(Interface.Description, "^(?i)(transit:|internet:|inet:):? ", "$1") &&
            ClassifyProviderRegex(Interface.Description, "^[^ ]+? ([^ ]+)", "$1") &&
            ClassifyExternal()
          - ClassifyInternal()
        default-sampling-rate: 1
```

Thank you @vincentbernat
