### DISCUSSION TITLE
Standalone Install Guide

### DISCUSSION THREAD

**Discussion by dbray925** [akvorado/akvorado#1513] [Q&A]
I have seen a few topics come up about non-Docker installs, standalone installs, separate VM installs, enterprise installs, using existing Kafa, or ClickHouse installs....etc. However, I haven't really seen any detailed guides on performing such installs. Thought I would take a stab at it, as this is what worked for us. This was all done on a Rocky Linux 8 server.

### Install some initial needed repos and apps
```
sudo dnf install epel-release -y
sudo dnf -y install GeoIP geoipupdate java-21-openjdk-headless
```

### Create a service account for Akvorado and some default directories
```
export NEWUSER='akvorado'
export NEWUID='100000'
export DESCRIPTION="Service Account for $NEWUSER"
export USERHOMESPACE="/opt/akvorado"
sudo useradd -r -c "$DESCRIPTION" -d $USERHOMESPACE -u $NEWUID $NEWUSER
sudo groupmod -g $NEWUID $NEWUSER
sudo mkdir $USERHOMESPACE
sudo chown -R $NEWUSER. $USERHOMESPACE
sudo chmod g+rwx -R /opt/akvorado/
sudo -u akvorado mkdir -p /opt/akvorado/bin
sudo -u akvorado mkdir -p /opt/akvorado/etc/kafka/
sudo -u akvorado mkdir -p /opt/akvorado/etc/orchestrator/
```

### Update rsyslog and logrotate
```
sudo mkdir /var/log/akvorado
sudo chown -R akvorado:akvorado /var/log/akvorado
sudo vim /etc/rsyslog.d/akvorado.conf
```
```
#/etc/rsyslog.d/akvorado.conf

# Kafka
if $programname == 'zookeeper-server-start.sh' then /var/log/akvorado/kafka-zookeeper.log
&stop

if $programname == 'kafka-server-start.sh' then /var/log/akvorado/kafka-server.log
&stop

# Akvorado Orchestrator, Outlet, Inlet, and Console
if $programname == 'akvorado' and \
$msg contains 'akvorado/outlet' then /var/log/akvorado/akvorado-outlet.log
&stop

if $programname == 'akvorado' and \
$msg contains 'akvorado/inlet' then /var/log/akvorado/akvorado-inlet.log
&stop

if $programname == 'akvorado' and \
($msg contains 'akvorado/console' or \
$msg contains 'akvorado/common/httpserver') then /var/log/akvorado/akvorado-console.log
&stop

if $programname == 'akvorado' then /var/log/akvorado/akvorado-orchestrator.log
&stop
```

```
sudo vim /etc/logrotate.d/akvorado
```
```
/var/log/akvorado/*.log
{
    create 664 akvorado akvorado
    su akvorado akvorado
    missingok
    sharedscripts
    compress
    delaycompress
    size 100M
    daily
    rotate 1
    postrotate
    /bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
    endscript
}

```
```
sudo systemctl restart rsyslog
```

### Install ClickHouse (Database)
```
sudo yum config-manager -y --add-repo https://packages.clickhouse.com/rpm/clickhouse.repo
sudo dnf -y install clickhouse-server clickhouse-client
sudo dnf -y install https://github.com/Altinity/clickhouse-backup/releases/download/v2.6.4/clickhouse-backup-2.6.4-1.x86_64.rpm
sudo systemctl enable --now clickhouse-server
sudo systemctl stop clickhouse-server
sudo sed -i -e 's/<level>trace<\/level>/<level>error<\/level>/' /etc/clickhouse-server/config.xml
sudo vim /var/lib/clickhouse/format_schemas/flow-LAABIGYMRYZPTGOYIIFZNYDEQM.proto
```
```
syntax = "proto3";

message FlowMessagevLAABIGYMRYZPTGOYIIFZNYDEQM {
 enum Boundary { UNDEFINED = 0; EXTERNAL = 1; INTERNAL = 2; }

 uint64 TimeReceived = 1;
 uint64 SamplingRate = 2;
 bytes ExporterAddress = 3;
 string ExporterName = 4;
 string ExporterGroup = 5;
 string ExporterRole = 6;
 string ExporterSite = 7;
 string ExporterRegion = 8;
 string ExporterTenant = 9;
 bytes SrcAddr = 10;
 bytes DstAddr = 11;
 uint32 SrcNetMask = 12;
 uint32 DstNetMask = 13;
 uint32 SrcAS = 14;
 uint32 DstAS = 15;
 repeated uint32 DstASPath = 18;
 repeated uint32 DstCommunities = 19;
 repeated uint32 DstLargeCommunitiesASN = 20;
 repeated uint32 DstLargeCommunitiesLocalData1 = 21;
 repeated uint32 DstLargeCommunitiesLocalData2 = 22;
 string InIfName = 23;
 string OutIfName = 24;
 string InIfDescription = 25;
 string OutIfDescription = 26;
 uint32 InIfSpeed = 27;
 uint32 OutIfSpeed = 28;
 string InIfConnectivity = 29;
 string OutIfConnectivity = 30;
 string InIfProvider = 31;
 string OutIfProvider = 32;
 Boundary InIfBoundary = 33;
 Boundary OutIfBoundary = 34;
 uint32 EType = 35;
 uint32 Proto = 36;
 uint32 SrcPort = 37;
 uint32 DstPort = 38;
 uint64 Bytes = 39;
 uint64 Packets = 40;
 uint32 ForwardingStatus = 41;
}
```
```
sudo systemctl restart clickhouse-server
```
Monitor the log file:
```
sudo tail -f -n 1000 /var/log/clickhouse-server/clickhouse-server.log
```
Setup the backup script 
```
sudo mkdir /opt/clickhouse-scripts
sudo vim /opt/clickhouse-scripts/backups.sh
```
```
#!/bin/sh
 
#
# /opt/clickhouse-scripts/backups.sh
#
 
[[ -d /var/lib/clickhouse/backup ]] && rm -rf /var/lib/clickhouse/backup
clickhouse-backup create -t default.flows > /var/log/clickhouse-server/clickhouse-backup.log 2>&1
[[ -f /backups/mounted ]] && rsync -a --delete --numeric-ids --update /var/lib/clickhouse/backup/ /backups/latest/clickhouse
```
NOTE: /backups/ is an NFS mount to remote Backup server
```
sudo chmod +x /opt/clickhouse-scripts/backups.sh
sudo vim /etc/cron.d/akvorado
```
```
#/etc/cron.d/akvorado

SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=root

# Monthly (day 1) update GeoIP databases
0 0 1 * * root geoipupdate && chmod go+rx -R /usr/share/GeoIP

# Backup ClickHouse databases daily @ 3am
0 3 * * * root /opt/clickhouse-scripts/backups.sh
```

### Install Kafka
```
export KAFKA='kafka_2.13-3.9.0'
sudo -u akvorado wget https://downloads.apache.org/kafka/3.9.0/"$KAFKA".tgz -O /tmp/"$KAFKA".tgz
sudo -u akvorado tar -xvf /tmp/"$KAFKA".tgz -C /opt/akvorado/
[[ -d /opt/akvorado/kafka ]] && sudo rm /opt/akvorado/kafka
sudo -u akvorado ln -sfv /opt/akvorado/$KAFKA /opt/akvorado/kafka
sudo -u akvorado vim /opt/akvorado/etc/kafka/zookeeper.properties
```
```
dataDir=/opt/akvorado/var/lib/kafka/zookeeper
clientPort=2181
maxClientCnxns=0
admin.enableServer=false
```
```
sudo -u akvorado vim /opt/akvorado/etc/kafka/server.properties
```
```
broker.id=0
num.network.threads=3
num.io.threads=8
socket.send.buffer.bytes=102400
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600
log.dirs=/opt/akvorado/var/lib/kafka/logs
num.partitions=1
num.recovery.threads.per.data.dir=1
offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1
log.retention.hours=8
log.retention.bytes=1073741824
log.segment.bytes=1073741824
log.retention.check.interval.ms=300000
zookeeper.connect=localhost:2181
zookeeper.connection.timeout.ms=18000
group.initial.rebalance.delay.ms=0
```
```
sudo vim /etc/systemd/system/akvorado-kafka-zookeeper.service
```
```
[Unit]
Description=Akvorado - Apache Kafka Zookeeper
Documentation=http://zookeeper.apache.org
Requires=network.target remote-fs.target
After=network.target remote-fs.target

[Service]
Type=simple
User=akvorado
Group=akvorado
ExecStart=/opt/akvorado/kafka/bin/zookeeper-server-start.sh /opt/akvorado/etc/kafka/zookeeper.properties
ExecStop=/opt/akvorado/kafka/bin/zookeeper-server-stop.sh
Restart=on-abnormal

[Install]
WantedBy=multi-user.target
```
```
sudo vim /etc/systemd/system/akvorado-kafka-server.service
```
```
[Unit]
Description=Akvorado - Apache Kafka Server
Documentation=http://kafka.apache.org/documentation.html
Requires=akvorado-kafka-zookeeper.service

[Service]
Type=simple
User=akvorado
Group=akvorado
ExecStart=/opt/akvorado/kafka/bin/kafka-server-start.sh /opt/akvorado/etc/kafka/server.properties
ExecStop=/opt/akvorado/kafka/bin/kafka-server-stop.sh
Restart=on-abnormal

[Install]
WantedBy=multi-user.target
```
```
sudo systemctl daemon-reload
sudo systemctl enable --now akvorado-kafka-zookeeper.service
sudo systemctl enable --now akvorado-kafka-server.service
```
Monitor the logs
```
sudo tail -f -n 1000 /var/log/akvorado/kafka-zookeeper.log
sudo tail -f -n 1000 /var/log/akvorado/kafka-server.log
```

### Install Akvorado Orchestrator
```
export AKVORADO='v2.0.3'
sudo -u akvorado wget https://github.com/akvorado/akvorado/releases/download/$AKVORADO/akvorado-amd64 -O /opt/akvorado/bin/akvorado
sudo -u akvorado chmod +x /opt/akvorado/bin/akvorado
sudo -u akvorado vim /opt/akvorado/etc/orchestrator/config.yaml
```
```
---
reporting:
    logging: {}
    metrics: {}

http:
    listen: :8080
    profiler: true
    cache:
        type: memory
kafka:
    topic: flows
    brokers:
        - 127.0.0.1:9092
    version: 3.3.1
    topic-configuration:
        num-partitions: 1
        replication-factor: 1
        config-entries:
          segment.bytes: 1073741824
          retention.ms: 86400000 # 1 day
          cleanup.policy: delete
          compression.type: producer

geoip:
    optional: true
    asn-database: /usr/share/GeoIP/GeoLite2-ASN.mmdb
    geo-database: /usr/share/GeoIP/GeoLite2-Country.mmdb

clickhouse:
    servers:
        - 127.0.0.1:9000
    kafka:
        consumers: 4
    networks:
      10.10.10.0/24:
        name: Management
        role: Management
    network-sources: []
    orchestrator-url: http://127.0.0.1:8080

outlet:
      http:
        listen: :8083
        profiler: true
        cache:
            type: memory
      metadata:
        workers: 5
        providers:
              type: snmp
              securityparameters:
                username: SNMPUSERNAME
                authentication-protocol: sha
                authentication-passphrase: 'SNMPSHAPASS'
                privacy-protocol: aes
                privacy-passphrase: 'SNMPAESPASS'
      core:
        workers: 5
        exporter-classifiers: []
        interface-classifiers: []
        default-sampling-rate: 1

inlet:
    - reporting:
        logging: {}
        metrics: {}
      http:
        listen: :8081
        profiler: true
        cache:
            type: memory
      kafka:
        compression-codec: none
      flow:
        inputs:
            - decoder: netflow
              listen: :9995
              queuesize: 100000
              receive-buffer: 10485760
              type: udp
              workers: 5

console:
    - reporting:
        logging: {}
        metrics: {}
      http:
        listen: :8082
        profiler: true
        cache:
            type: memory
      default-visualize-options:
        graphtype: stacked
        start: 12 hours ago
        end: now
        filter: ''
        dimensions:
            - ExporterName
            - SrcAddr
            - DstAddr
        limit: 10
        bidirectional: false
        previousperiod: false
      homepage-top-widgets:
        - src-as
        - src-port
        - protocol
        - etype
      homepage-graph-filter: ''
      clickhouse:
        servers:
            - 127.0.0.1:9000
        database: default
        username: default
      auth:
        headers:
            login: Remote-User
            name: Remote-Name
            email: Remote-Email
            logouturl: X-Logout-URL
        defaultuser:
            login: __default
            name: Default User
            email: ""
            logouturl: ""
```
```
sudo vim /etc/systemd/system/akvorado-orchestrator.service
```
```
[Unit]
Description=Akvorado - Orchestrator
Documentation=https://demo.akvorado.net/docs
Requires=network.target remote-fs.target
After=network.target remote-fs.target akvorado-kafka-server.service

[Service]
Type=simple
User=akvorado
Group=akvorado
ExecStart=/opt/akvorado/bin/akvorado orchestrator /opt/akvorado/etc/orchestrator/config.yaml
Restart=on-abnormal

[Install]
WantedBy=multi-user.target
```
```
sudo systemctl daemon-reload
sudo systemctl enable --now akvorado-orchestrator.service
```
Monitor the log file
```
sudo tail -f -n 1000 /var/log/akvorado/akvorado-orchestrator.log
```

### Install Akvorado Outlet
```
sudo vim /etc/systemd/system/akvorado-outlet.service
```
```
[Unit]
Description=Akvorado - Outlet
Documentation=https://demo.akvorado.net/docs
Requires=network.target remote-fs.target akvorado-orchestrator.service
After=network.target remote-fs.target

[Service]
Type=simple
User=akvorado
Group=akvorado
ExecStart=/opt/akvorado/bin/akvorado outlet http://127.0.0.1:8080
Restart=on-abnormal

[Install]
WantedBy=multi-user.target
```
```
sudo systemctl daemon-reload
sudo systemctl enable --now akvorado-outlet.service
```
Monitor log file
```
sudo tail -f -n 1000 /var/log/akvorado/akvorado-outlet.log
```

### Install Akvorado Inlet (NetFlow service)
```
sudo vim /etc/systemd/system/akvorado-inlet.service
```
```
[Unit]
Description=Akvorado - Inlet
Documentation=https://demo.akvorado.net/docs
Requires=network.target remote-fs.target akvorado-orchestrator.service
After=network.target remote-fs.target

[Service]
Type=simple
User=akvorado
Group=akvorado
ExecStart=/opt/akvorado/bin/akvorado inlet http://127.0.0.1:8080
Restart=on-abnormal

[Install]
WantedBy=multi-user.target
```
```
sudo systemctl daemon-reload
sudo systemctl enable --now akvorado-inlet.service
```
Monitor log file
```
sudo tail -f -n 1000 /var/log/akvorado/akvorado-inlet.log
```

### Install Akvorado Console (WebUI)
```
sudo vim /etc/systemd/system/akvorado-console.service
```
```
[Unit]
Description=Akvorado - Console (WebUI)
Documentation=https://demo.akvorado.net/docs
Requires=network.target remote-fs.target akvorado-orchestrator.service
After=network.target remote-fs.target

[Service]
Type=simple
User=akvorado
Group=akvorado
ExecStart=/opt/akvorado/bin/akvorado console http://127.0.0.1:8080
Restart=on-abnormal

[Install]
WantedBy=multi-user.target
```
```
sudo systemctl daemon-reload
sudo systemctl enable --now akvorado-console.service
```
Monitor the log file
```
sudo tail -f -n 1000 /var/log/akvorado/akvorado-console.log
```

With all that done, you _should_ be able to access the console via http://akvorado.server.name.here:8082/ or if you want to use an Apache proxy, then configure something like:

```
<Proxy *>
    Order deny,allow
    Allow from all
</Proxy>
ProxyPreserveHost On
<Location "/">
    ProxyPass "http://127.0.0.1:8082/"
    ProxyPassReverse "http://127.0.0.1:8082/"

    AuthName "Use Your LDAPN Credentials"
    AuthType Basic
    AuthBasicProvider ldap
    AuthLDAPInitialBindAsUser on
    AuthLDAPInitialBindPattern (.+) cn=$1,ou=Users,dc=domain,dc=lan
    AuthLDAPCompareAsUser on
    AuthLDAPURL "ldaps://openldap.domain.lan/ou=Users,dc=domain,dc=lan?uid?sub?(objectClass=*)"
    Require ldap-group cn=DevOps,ou=Groups,dc=domain,dc=lan
    RequestHeader set Remote-User %{AUTHENTICATE_uid}e
</Location>
```

Now, each of the above pieces could, with little effort, be deployed onto separate servers, point at existing servers (Kafka, ClickHouse, etc), or adjusted to fit your needs. You would just need to update the obvious URLs to point to the proper locations.

Hope this helps someone. Please respond with any questions, comments, or suggestions. Thanks!

**Comment by kronicklez** [comment]
Hi @dbray925 ,

Is it possible do all in one server only?  

Thanks and appreciate your feedback

**Reply by dbray925** [reply]
Yes, of course. That's how the default docker method is done, and that's how we're currently running it. We'll expand it to additional servers if the time comes that it feels necessary, but for now every thing seems fine on one server.

**Reply by kronicklez** [reply]
Hi @dbray925 ,

Thanks for your feedback. It look interesting. I will try it based on your step. Anything issue i will update.

Thanks

**Reply by kronicklez** [reply]
Hi @dbray925 ,

I facing error in this step below. Appreciate your feedback

sudo vim /etc/systemd/system/akvorado-clickhouse-server.service
[Unit]
Description=Akvorado - ClickHouse Server
Requires=network-online.target

[Service]
Type=notify
User=akvorado
Group=akvorado
Restart=always
TimeoutStopSec=infinity
Environment=CLICKHOUSE_WATCHDOG_NO_FORWARD=1
TimeoutStartSec=0
ExecStart=/opt/akvorado/bin/clickhouse server --config /opt/akvorado/etc/clickhouse/akvorado.xml
LimitCORE=infinity
LimitNOFILE=500000

[Install]
WantedBy=multi-user.target
sudo systemctl daemon-reload
sudo systemctl enable --now akvorado-clickhouse-server


[root@localhost ~]# sudo systemctl enable --now akvorado-clickhouse-server
Created symlink /etc/systemd/system/multi-user.target.wants/akvorado-clickhouse-server.service → /etc/systemd/system/akvorado-clickhouse-server.service.
**Job for akvorado-clickhouse-server.service failed because the control process exited with error code.**
See "systemctl status akvorado-clickhouse-server.service" and "journalctl -xe" for details.

**Reply by kronicklez** [reply]
Hi @dbray925 ,

I'm also get error below:

[root@localhost ~]# sudo tail -f -n 1000 /var/log/akvorado/clickhouse-server.log
tail: cannot open '/var/log/akvorado/clickhouse-server.log' for reading: No such file or directory
tail: no files remaining


[root@localhost ~]# sudo -u akvorado wget $REPO/repos/opt/akvorado/"$KAFKA".tgz -O /tmp/"$KAFKA".tgz
/repos/opt/akvorado/kafka_2.13-3.9.0.tgz: Scheme missing.

**Reply by dbray925** [reply]
For the ClickHouse error, you'll need to troubleshoot that a little more. Review what it says (journalctl or systemd status) and see why your ClickHouse isn't launching. That's also why you aren't getting the log file to review, because ClickHouse isn't launching. You might have to head over to ClickHouse's site, and check their troubleshooting guides.

That $REPO entry has been updated. It should've been:
sudo -u akvorado wget https://downloads.apache.org/kafka/3.9.0/"$KAFKA".tgz -O /tmp/"$KAFKA".tgz

**Reply by kronicklez** [reply]
Hi @dbray925 ,

Noted on that. I'm will try look again. Previously i thought your step is complete just follow only but look like it different. For now i'm will stay back using docker.

Thanks

**Reply by panniqi** [reply]
I got similar tail errors about directory missing for: 
- kafka-zookeeper.log
- kafka-server.log
- akvorado-orchestrator.log
- akvorado-inlet.log
- akvorado-console.log

In addition, there are many errors of this type in the Clickhouse logs:
`[ 3593 ] {} <Error> StorageKafka (flows_LAABIGYMRYZPTGOYIIFZNYDEQM_raw): [client.id:ClickHouse-srv-fc-01-default-flows_LAABIGYMRYZPTGOYIIFZNYDEQM_raw-3] [rdk:ERROR] [thrd:app]: ClickHouse-srv-fc-01-default-flows_LAABIGYMRYZPTGOYIIFZNYDEQM_raw-3#consumer-4: 127.0.0.1:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 129 identical error(s) suppressed)`

> Seems something went wrong with port 9092 and installation/setting🤔

**Reply by dbray925** [reply]
Double check the above "Update rsyslog and logrotate" part, especially the mkdir command. Also, sounds like you might need to double check the overall rsyslog install, and troubleshoot that before proceeding. 

As for ClickHouse, I see the same/similar "Connection refused" errors scroll by in my logs, but everything is still working as expected. We might have to check over the ClickHouse documentation or site for further troubleshooting there.

**Comment by dbray925** [comment]
Edited ClickHouse documentation to use RPM based install instead of the binary. Also updated ClickHouse backup instructions.

**Comment by gregorysch** [comment]
Thanks for this time-saving documentation. Really appreciated.

**Comment by bwlee77** [comment]
hi @dbray925 
I appreciate your thoughtful manual. But I'm in trouble.
I have successfully installed on Rocky 8 Linux as per the manual and all daemons are running normally. However, the 'flow' data sent from the switch reaches the server interface but is not loaded into the DB.

What part did I miss? What else should I look into?
Even running it with Docker, it's the same.

Please help.

**Reply by dbray925** [reply]
> What part did I miss? What else should I look into? Even running it with Docker, it's the same.

Sorry, not much for me to go on. Without seeing logs and things like that, I can guess. Check Kafka and the logs, as Kafka should be the service pushing the flows into the database. The API was very helpful for me initially setting all this up. What does this look like for you?

`curl -s http://127.0.0.1:8081/api/v0/inlet/metrics | grep '^akvorado_inlet' |  grep _error`

If both the non-docker install (my instructions above) and the default docker install are _both_ not working for you, then I would have to suspect it is something with the kind of flows, types of devices, that is being sent. The above API should hopefully shed some light.

Good luck!

**Reply by bwlee77** [reply]
Thanks for your reply. I got the following result using the api code you provided.
Note that I am not using snmp. How can I do the next step?


`# curl -s http://127.0.0.1:8081/api/v0/inlet/metrics | grep '^akvorado_inlet'|grep error
akvorado_inlet_core_flows_errors_total{error="SNMP cache miss",exporter="000.000.000.14"} 23435
akvorado_inlet_metadata_provider_snmp_poller_error_requests_total{error="get",exporter="000.000.000.14"} 19 `

**Reply by bwlee77** [reply]
I was wondering about the error message above. I guessed that the error occurred because snmp was not set in the orchestrator settings. I tried adding the snmp syntax to the orchestrator yaml file. As a result, I was able to confirm that a normal graph was created.
Thank you for all the help and hints.

**Comment by tcroghan-LCT** [comment]
Thank you for the guide, I ran into a couple snags and here's my notes to possibly help others. 

Using Rocky Linux 8, I needed to add the EPEL repository using: 
`sudo dnf install epel-release -y`

To add the clickhouse repo, I had to add a space between "yum" and "config-manager" instead of the hyphen. 
`sudo yum config-manager -y --add-repo https://packages.clickhouse.com/rpm/clickhouse.repo`

Lastly, the firewall needed to allow 8082 from external. (Note, I used Cockpit, but these "should" be the correct commands)
```
firewall-cmd --zone=public --add-port=8082/tcp
firewall-cmd --runtime-to-permanent
```

**Reply by dbray925** [reply]
We use our own internally hosted repos, so I didn't document the epel. I've updated the above to include that now, thanks. 

Fixed the yum-config typo, thanks.

If you use Apache (or any HTTP proxy) like I do, you do not need any ports but 80 and/or 443 opened externally. 

Glad you liked the guide :-)

**Comment by Z3r0XG** [comment]
Hello, following your guide I ran into this error on startup:

Jun 04 22:30:49 avorkado akvorado[42025]: {"level":"error","error":"no such file or directory","time":"2025-06-04T22:30:49-04:00","caller":"akvorado/orchestrator/geoip/root.go:135","module":"akvorado/orchestrator/geoip","message":"cannot watch database directory"}
Jun 04 22:30:49 avorkado akvorado[42025]: Error: unable to start component: cannot watch database directory: no such file or directory

This leads to further issues with the log files missing as described in a previous comment.

**Reply by dbray925** [reply]
Looks like you'll need to research the GeoIP part I documented above, and confirm that is working outside of Akvorado first. You didn't give much troubleshooting for me to go on, so I'm really not sure. That's all I can suggest for now. 

For example, I can see this as my normal user:
`ls -lah /usr/share/GeoIP/GeoLite2-ASN.mmdb`
> -rw-r-xr-x 1 root root 9.8M Jun  1 00:00 /usr/share/GeoIP/GeoLite2-ASN.mmdb

`ls -lah /usr/share/GeoIP/GeoLite2-Country.mmdb`
>-rw-r-xr-x 1 root root 8.9M Jun  1 00:00 /usr/share/GeoIP/GeoLite2-Country.mmdb

Do you see something like that, or at least something similar? It might be permissions on the GeoIP database.

**Comment by Si-Richards** [comment]
I 'loosely' followed it and made some alterations.

Here are some of the issues i had getting a working yaml for my setup that might help other people.

1. No data being collected! - Check your exporter agent mappings. You can see if this is an issue from a TCPdump.
2. No data on the front widgets ? - Just classify everything as external then once data is populating you can refine it.

Thanks for the useful guide!

```
inlet:
  reporting:
    logging: {}
    metrics: {}
  http:
    listen: 0.0.0.0:8081
    profiler: true
    cache:
      type: memory
  kafka:
    compression-codec: none
  metadata:
    workers: 10
    provider:
      type: snmp
      agents:
        xx.xx.x.xxx: x.xx.xx.xx
        xx.xx.x.xxx: x.xx.xx.xxx
      credentials:
        x.xx.xx.xx:
          communities: public
        x.xx.xx.xxx:
          communities: public
  flow:
    inputs:
      - decoder: sflow
        listen: 0.0.0.0:6343
        receive-buffer: 20485760
        type: udp
        workers: 12
  core:
    workers: 10
    exporter-classifiers: []
    interface-classifiers:
      - ClassifyExternal()
    default-sampling-rate: 1
    asn-providers: [ flow-except-private, bmp, routing ]
```
