### DISCUSSION TITLE
ipfixprobe as exporter

### DISCUSSION THREAD

**Discussion by FestplattenSchnitzel** [akvorado/akvorado#1547] [Q&A]
I'm using [ipfixprobe](https://github.com/CESNET/ipfixprobe) as exporter with the following config:
`ipfixprobe -i "dpdk;p=0,1;e=-c 0x1 -a 0000:02:00.0 -a 0000:02:00.1" -p pstats -p tls -p basicplus -p idpcontent -p quic -p phists -p wg -p ovpn -p ssadetector -p nettisa -p http -s 'cache;size=22;active=300;inactive=65' -o 'ipfix;u;host=127.0.0.1;port=2056;dir=1337;t=30' -t /var/run/ipfixprobe`.  There's also a [samplicator](https://github.com/sleinen/samplicator/) running on the same machine as the ipfixprobe, which distributes the packets to multiple receivers.

At the Akvorado, a static inlet[0].metadata.providers entry is necessary of course:
```yaml
- type: static
  exporters:
    203.0.113.113:
      name: ipfixprobe
      default:
        name: unknown
        description: Unknown interface
        speed: 1000
      ifindexes:
        1337:
          name: ipfixprobe
          description: ipfixprobe
          speed: 1000
```

The setup works pretty well, however there is significantly fewer traffic throughput displayed by Akvorado when the ipfixprobe `cache: S split (Split biflows into uniflows)` setting is enabled.  I don't know why though.
