### DISCUSSION TITLE
skip to next provider for missing interfaces in static metadata

### DISCUSSION THREAD

**Discussion by bogi788** [akvorado/akvorado#1572] [Q&A]
It appears that currently the static metadata provider is used for all interfaces on an exporter and only skips to the next provider if no exporter matches the IP address. We would however like to additionally skip for missing interfaces if no defaults were given for its exporter.

For example with

```
exporters:
  1.2.3.4:
    ifindexes:
      1:
        description: test interface
        name: ae0.0
        speed: 100000
    name: exporter1
```

as static metadata we would like to fall back to SNMP for interfaces from 1.2.3.4 with an index other than 1.

Is this feature already planned or would a MR be welcome?
