### DISCUSSION TITLE
Retention time for ip addresses and ports

### DISCUSSION THREAD

**Discussion by Tito-aix** [akvorado/akvorado#1579] [Q&A] [answered]
Hi Vincent & community,

Regarding data sensitivity, is there a solution to know the retention time for ip addresses and ports ?

And also can we change these settings somewhere ?
Maybe directly in the ClickHouse DB container ?

Thanks & Merry Christmas :)

Thierry

**Comment by fatherfbi** [comment]
The akvorado database consists of 4 tables.
```

   ┌─table────────┬─size───────┬─oldest─────────┐
1. │ flows        │ 163.67 MiB │ 20241224022400 │
2. │ flows_1h0m0s │ 4.71 MiB   │ 20241223191200 │
3. │ flows_5m0s   │ 15.51 MiB  │ 20241223191200 │
4. │ flows_1m0s   │ 19.95 MiB  │ 20241218135512 │
   └──────────────┴────────────┴────────────────┘

```
Data with IP addresses and ports are in the **flows** table. Storage time is determined by the configuration.

Example configuration
```
resolutions:
  - interval: 0
    ttl: 360h  # 15 days
  - interval: 1m
    ttl: 168h  # 1 week
  - interval: 5m
    ttl: 2160h # 3 months
  - interval: 1h
    ttl: 8760h # 1 year
```
Where
```
resolutions:
  - interval: 0 < flows table
    ttl: 360h  # 15 days
  - interval: 1m < flows_1m0s table
    ttl: 168h  # 1 week
  - interval: 5m < flows_5m0s table
    ttl: 2160h # 3 months
  - interval: 1h < flows_1h0m0s table
    ttl: 8760h # 1 year
```

**Reply by Tito-aix** [reply]
Hello and thanks for your prompt response,

So if I sum up, ip addresses and ports are stored only in the "flows" table and kept for 15 days and we can change this config in the yaml file ?
Ip addresses and ports are not present anymore in the 3 other tables right ?

**Reply by fatherfbi** [reply, marked as answer]
That's right, data with IP addresses and ports are stored only in the flows table, then the internal aggregation mechanism in Clickhouse is launched, which aggregates data into minute segments, but during aggregation IP addresses and ports are deleted.
You can set the data storage time in akvorado.yaml

Example configuration
```
cat config/akvorado.yaml
---
# This configuration file is documented in docs/02-configuration.md.
# You can get all default values with `akvorado orchestrator /dev/null
# --dump --check` or `docker compose run akvorado-orchestrator
# orchestrator /dev/null --dump --check`.

kafka:
  topic: flows
  version: 3.3.1
  brokers:
    - kafka:9092
  topic-configuration:
    num-partitions: 8
    replication-factor: 1
    config-entries:
      # The retention policy in Kafka is mainly here to keep a buffer
      # for ClickHouse.
      segment.bytes: 1073741824
      retention.ms: 86400000 # 1 day
      cleanup.policy: delete
      compression.type: producer

geoip:
  optional: true
  # When running on Docker, these paths are inside the container. By default,
  # IPinfo databases are used. (https://ipinfo.io/)
  asn-database:
    - /usr/share/GeoIP/asn.mmdb
  geo-database:
    - /usr/share/GeoIP/country.mmdb
  # If you want to use MaxmindDB, check `.env`, `docker-compose-maxmind.yml` and
  # update these paths:
  #asn-database:
  # - /usr/share/GeoIP/GeoLite2-ASN.mmdb
  #geo-database:
  # - /usr/share/GeoIP/GeoLite2-Country.mmdb

clickhouse:
  orchestrator-url: http://akvorado-orchestrator:8080
  kafka:
    consumers: 10
  resolutions:
    - interval: 0
      ttl: 168h  # 7 days
    - interval: 1m
      ttl: 720h  # 1 months
    - interval: 5m
      ttl: 2160h # 3 months
    - interval: 1h
      ttl: 4320h # 6 months
  system-log-ttl: 0
  servers:
    - clickhouse:9000
  prometheus-endpoint: /metrics

  asns: []
  networks: []
  network-sources: []

inlet: !include "inlet.yaml"
console: !include "console.yaml"

```

Q: Ip addresses and ports are not present anymore in the 3 other tables right ?
A: Yep
