### DISCUSSION TITLE
Chart not shown

### DISCUSSION THREAD

**Discussion by Koyorice** [akvorado/akvorado#1595] [Q&A]
![image](https://github.com/user-attachments/assets/a42aa1f1-5974-4870-85fa-b972eb504f02)
I have configured SNMP and sFlow, using Linux snmpd and https://github.com/sflow/host-sflow
But the chart is not displayed and AS always displays Other, the following is the error and that continues to increase
```
$ curl -s http://127.0.0.1:8080/api/v0/inlet/metrics | grep '^akvorado_inlet' | grep _error
akvorado_inlet_core_flows_errors_total{error="input and output interfaces missing",exporter="x.x.x.x"} 15
```

The following is the configuration of inlet

```
metadata:
  workers: 10
  provider:
    type: snmp
    security-parameters:
      user-name: user
      authentication-protocol: SHA512
      authentication-passphrase: passphrase
      privacy-protocol: AES256
      privacy-passphrase: passphrase
```

Thanks!
