### DISCUSSION TITLE
SNMP configuration of different versions for different devices?

### DISCUSSION THREAD

**Discussion by netcedec** [akvorado/akvorado#1606] [Q&A] [answered]
How to configure different versions for snmp in the file akvorado/config/inlet.yaml ? 

For example, I have the following devices: 

192.168.1.1 support SNMP v3
192.168.1.2 support only SNMP v2
192.168.1.3 support SNMP v3

My try in config:

```
 provider:
    type: snmp
    communities:
      192.168.1.2: test1
    security-parameters:
      ::/0:
        username: banny
        authentication-protocol: sha
        privacy-protocol: aes
        authentication-passphrase: test
        privacy-passphrase: test

```

It's don't work.
