### DISCUSSION TITLE
Match ipv6 subnet  using SrcAddr and DstAddr

### DISCUSSION THREAD

**Discussion by taofineberg** [akvorado/akvorado#1619] [Q&A]
I am matching customer names to the flow data using a custom dictionary. This is working perfectly with this schema:

```
custom-dictionaries:
  customers:
    layout: complex_key_hashed
    keys:
      - name: addr
        type: String
    attributes:
      - name: Name
        type: String
        label: CustomerName
    source: /etc/akvorado/customers.csv
    dimensions:
      - SrcAddr
      - DstAddr
```

The issue I am having is that an assigned subnet is not being matched to the customer name. 
This makes sense as the assigned subnet is 2505:1440:feed:ee::/64 but the source/destination is 2505:1440:feed:ee::1004.

I have tried to match addr with DstNetPrefix/SrcNetPrefix, but it looks like due to that being a calculated field in ClickHouse, it is not possible.
  dimensions:
```
    - DstNetPrefix
    - SrcNetPrefix   

```
As a workaround, I have added each customer to the networks, but that means I have the customer name in two places IPv4 and IPv6, and it is also harder to add additional metadata as the fields are set in the network schema.
Having a look at the code, it looks like maybe I need to do something around the matchdimension and matchdimensionsuffix but cannot find any documentation on this.

          matchdimension: ""
          matchdimensionsuffix: ""

Any advice on how to match the customer ipv6 subnet subnet using the custom dictionary?

Thanks in advance.
PS. this is a great product, and I am very impressed with the performance and ease of use
