### DISCUSSION TITLE
Force akvorado to update metadata cache

### DISCUSSION THREAD

**Discussion by riddler63** [akvorado/akvorado#1654] [Q&A]
Hello all,

How I can force akvorado to update metadata cache obtained by SNMP or/and GNMI?

I've updated the description of interfaces, but it still shows the old values and cannot parse it correctly.

Also, maybe it will be nice to mention dimension for "cache-duration", "cache-refresh" and "cache-check-interval" and provide some configuration example.

**Comment by adjiekrazz** [comment]
You can check the default configuration with `docker compose run akvorado-orchestrator orchestrator /dev/null --dump --check`.

Here are the configuration example for metadata cache that i got from default configuration:
```
metadata:
        cacheduration: 30m0s
        cacherefresh: 1h0m0s
        cachecheckinterval: 2m0s
        cachepersistfile: ""
```
