### DISCUSSION TITLE
SNMP isn't pulling in full interface descriptions, how can we bypass?

### DISCUSSION THREAD

**Discussion by resonator** [akvorado/akvorado#1656] [Q&A]
I am troubleshooting our new install of Akvorado, everything is working right now except actually displaying the data in the webgui. I can see new flows coming in constantly on the "Last Flow" widget, but they are all being listed as "InIfBoundary    internal" which is causing them to not "count" as real flows for display.

The issue is that I am adding "Transit:" to our interface descriptions, but the descriptions on the "Last Flow" widget are just defaulting to the full name of the interface i.e. when adding a flow monitor to an interface GigabitEthernet0/0.200, the interface description in the "Last Flow " widget also says that, the actual description on the interface is not pulled in at all, is there anyway to bypass this? 

Like just classify all interfaces as external? Since I'm only adding the netflow monitor to external interfaces anyway?

**Comment by vincentbernat** [comment]
The classification is done on both incoming and outgoing interfaces, even if you only enable netflow on external interfaces.

There is a cache for SNMP. It should update every 30 minutes.

**Reply by resonator** [reply]
Thank you but my issue is that it seems Akvorado is seeing the interface description as literally "FastEthernet0/0/0" instead of the description that is configured on the interface, its been running for a few hours now and that is still the case, see my example attached:

![example-01](https://github.com/user-attachments/assets/4071396b-2d04-43e7-ac8d-724ee7ce808d)

I don't know if this is an SNMP error, since this device is rather old, or if it is something else. Basically what I'd like to know is there a way I can modify the regex under the inlet config to just match everything, so the description doesn't matter and everything sent to Akvorado is displayed?

My current config is: 

        interface-classifiers:
          - ClassifyConnectivityRegex(Interface.Description, "^(?i)(transit:|internet:|inet:):? ", "$1") &&
     
I tried to use:

        interface-classifiers:
          - ClassifyConnectivityRegex(Interface.Description, ".*", "$1") &&

I've also tried:

       interface-classifiers:
          - ClassifyConnectivityRegex(Interface.Description, "^(?i)(transit:|internet:|inet:|GigabitEthernet|FastEthernet):? ", "$1") &&


But none of these worked and everything was still classified as 'internal'. Is it possible there is some other issue here? I would think that matching "fastethernet" would match the description at least, but it doesn't seem to work either.

**Reply by fatherfbi** [reply]
> Thank you but my issue is that it seems Akvorado is seeing the interface description as literally "FastEthernet0/0/0" instead of the description that is configured on the interface, its been running for a few hours now and that is still the case, see my example attached:
> 
> ![example-01](https://private-user-images.githubusercontent.com/3943061/415311999-4071396b-2d04-43e7-ac8d-724ee7ce808d.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAwNzYyMjcsIm5iZiI6MTc0MDA3NTkyNywicGF0aCI6Ii8zOTQzMDYxLzQxNTMxMTk5OS00MDcxMzk2Yi0yZDA0LTQzZTctYWM4ZC03MjRlZTdjZTgwOGQuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAyMjBUMTgyNTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDUwNDI1OThlMWRlOWE4MjcxYmVlMDU5ZTVkYTJmM2I4Y2YzNDRmY2YzZTUwZTU3Y2VjZjA3ZmE0MTlhODI2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.jgOjArUQEGwv8Ksek3iX38bb_oRbKeizk7HAWxYqOhk)
> 
> I don't know if this is an SNMP error, since this device is rather old, or if it is something else. Basically what I'd like to know is there a way I can modify the regex under the inlet config to just match everything, so the description doesn't matter and everything sent to Akvorado is displayed?
> 
> My current config is:
> 
> ```
>     interface-classifiers:
>       - ClassifyConnectivityRegex(Interface.Description, "^(?i)(transit:|internet:|inet:):? ", "$1") &&
> ```
> 
> I tried to use:
> 
> ```
>     interface-classifiers:
>       - ClassifyConnectivityRegex(Interface.Description, ".*", "$1") &&
> ```
> 
> I've also tried:
> 
> ```
>    interface-classifiers:
>       - ClassifyConnectivityRegex(Interface.Description, "^(?i)(transit:|internet:|inet:|GigabitEthernet|FastEthernet):? ", "$1") &&
> ```
> 
> But none of these worked and everything was still classified as 'internal'. Is it possible there is some other issue here? I would think that matching "fastethernet" would match the description at least, but it doesn't seem to work either.

Show the description of the interface on the device itself.

**Reply by resonator** [reply]
Sure thing

![example2](https://github.com/user-attachments/assets/7172e258-be23-4143-b130-eaf161266a47)

**Reply by fatherfbi** [reply]
> Sure thing
> 
> ![example2](https://private-user-images.githubusercontent.com/3943061/415316321-7172e258-be23-4143-b130-eaf161266a47.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAwNzY1NTIsIm5iZiI6MTc0MDA3NjI1MiwicGF0aCI6Ii8zOTQzMDYxLzQxNTMxNjMyMS03MTcyZTI1OC1iZTIzLTQxNDMtYjEzMC1lYWYxNjEyNjZhNDcuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAyMjBUMTgzMDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTYzMmQ2N2U5NTE5OWEzMWY5ZDk0MTQwZjg2NTliMDU3MDRmNGU3NTk2YWViODQxN2VkMjgyZmVlNzVlMjBiMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lIBpXskfd7g8VgldgLxQMHMvBja2EVj5Dzjlmwq6zUc)

I see 2 options
1. Use static configuration
2. Figure out why the switch does not send the port description

**Reply by resonator** [reply]
I would love to not have to do static, but I'm running out of options..

Is the 'static providers' what you are referring to in the documentation? or is there another type of static configuration?

**Reply by fatherfbi** [reply]
> I would love to not have to do static, but I'm running out of options..
> 
> Is the 'static providers' what you are referring to in the documentation? or is there another type of static configuration?

That's right, "static provider"
There is nothing complicated in the setup, if you have any questions about the setup, I will be happy to help you.

**Reply by resonator** [reply]
Thank you, I appreciate it, I'm having a bit of a hard time inserting a static provider into my inlet.yml, here is a snippet that I have, although the inlet fails when trying to restart it, hopefully I'm just messing up a simple syntax:


```
kafka:
  compression-codec: zstd
metadata:
  workers: 10
  provider:
    type: static
      exporters:
        10.10.10.10:
          name: RTR-NAME
          default:
            name: unknown
            description: Unknown interface
            speed: 100
          ifindexes:
            14:
              name: Gig0/0
              description: Transit: Link
              speed: 1000
    type: snmp
    securityparameters:
      username: user-snmp
      authentication-protocol: sha
      authentication-passphrase: 'xxxxxx'
      privacy-protocol: aes
      privacy-passphrase: 'xxxxxx'
```

**Reply by fatherfbi** [reply]
> Thank you, I appreciate it, I'm having a bit of a hard time inserting a static provider into my inlet.yml, here is a snippet that I have, although the inlet fails when trying to restart it, hopefully I'm just messing up a simple syntax:
> 
> ```
> kafka:
>   compression-codec: zstd
> metadata:
>   workers: 10
>   provider:
>     type: static
>       exporters:
>         10.10.10.10:
>           name: RTR-NAME
>           default:
>             name: unknown
>             description: Unknown interface
>             speed: 100
>           ifindexes:
>             14:
>               name: Gig0/0
>               description: Transit: Link
>               speed: 1000
>     type: snmp
>     securityparameters:
>       username: user-snmp
>       authentication-protocol: sha
>       authentication-passphrase: 'xxxxxx'
>       privacy-protocol: aes
>       privacy-passphrase: 'xxxxxx'
> ```

```
kafka:
  compression-codec: zstd
metadata:
  workers: 10
  provider:
    - type: static
      exporters:
        10.10.10.10:
          name: RTR-NAME
          default:
            name: unknown
            description: Unknown interface
            speed: 100
          ifindexes:
            14:
              name: Gig0/0
              description: Transit: Link
              speed: 1000
    - type: snmp
      securityparameters:
        username: user-snmp
        authentication-protocol: sha
        authentication-passphrase: 'xxxxxx'
        privacy-protocol: aes
        privacy-passphrase: 'xxxxxx'
```
You forgot to put a hyphen before the types.

If you are using a docker installation, you can look at the container logs to understand where you made a syntax error.
```
docker container logs akvorado-akvorado-inlet-1
```
```
docker container logs akvorado-akvorado-orchestrator-1
```

**Reply by resonator** [reply]
Thank you for the commands to check the logs, that makes it easier. I'm a little confused though, I've added my interface statically and its showing the description that I set in the "Last Flow". So that is presumably working, although it still shows up as an 'internal' interface and no data is shown. 

However if I add a word like "Transit:" to the statically assigned interface description, the inlet now crashes, and I get the following error:

`Error: unable to parse YAML configuration file: at line 76 of akvorado.yaml: in inlet.yaml: yaml: line 18: mapping values are not allowed in this context`

So if I cant add mapping values to the static interface description, how am I going to get the interface to show as external?

**Reply by fatherfbi** [reply]
> Thank you for the commands to check the logs, that makes it easier. I'm a little confused though, I've added my interface statically and its showing the description that I set in the "Last Flow". So that is presumably working, although it still shows up as an 'internal' interface and no data is shown.
> 
> However if I add a word like "Transit:" to the statically assigned interface description, the inlet now crashes, and I get the following error:
> 
> `Error: unable to parse YAML configuration file: at line 76 of akvorado.yaml: in inlet.yaml: yaml: line 18: mapping values are not allowed in this context`
> 
> So if I cant add mapping values to the static interface description, how am I going to get the interface to show as external?

Show the configuration block with the error.

**Reply by fatherfbi** [reply]
For your convenience, I can attach a working configuration, just adapt it for yourself.

```
---
kafka:
  compression-codec: zstd
metadata:
  workers: 20
  providers:
    - type: static
      exporters:
        10.255.100.100:
          name: FFT-***
          default:
            name: unknown
            description: Unknown interface
            speed: 100
          ifindexes:
            571:
              name: ae1.390
              description: UPL GOOGLE
              speed: 300000
            592:
              name: ae1.698
              description: PNI AMAZON
              speed: 300000
            570:
              name: ae1.707
              description: IX DATA
              speed: 300000
            558:
              name: ae1.1527
              description: MPLS to another RS
              speed: 300000
            554:
              name: ae1.1599
              description: UPL APPLE
              speed: 300000
            529:
              name: ae1.4062
              description: IBGP RS-2
              speed: 300000
    - type: snmp
      communities:
        10.255.100.100: "er******wrf"
flow:
  inputs:
    - type: udp
      decoder: netflow
      listen: :2055
      workers: 20
      receive-buffer: 10485760
    - type: udp
      decoder: sflow
      listen: :6343
      workers: 20
      receive-buffer: 10485760
routing:
  provider:
    type: bmp
    listen: 0.0.0.0:10179
    collect-asns: true
    collect-aspaths: true
    collect-communities: true
core:
  workers: 20

  exporter-classifiers:
    - ClassifySiteRegex(Exporter.Name, "^([^-]+)-", "$1")
    - Exporter.Name startsWith "FFT-" && ClassifyRegion("Frankfurt")
  interface-classifiers:
    - |
      ClassifyConnectivityRegex(Interface.Description, "^(?i)(pni|ix|upl|):? ", "$1") &&
      ClassifyProviderRegex(Interface.Description, "^\\S+?\\s(\\S+)", "$1") &&
      ClassifyExternal()
    - ClassifyConnectivityRegex(Interface.Description, "^(?i)(dnl|ibgp|lt|mpls):? ", "$1") &&
      ClassifyInternal()
    - ClassifyInternal()
```

**Reply by resonator** [reply]
Thanks for the help with this, I've got at least the static interfaces showing as external now:

![example3](https://github.com/user-attachments/assets/697d6738-0910-4554-b958-5f4bf3d47145)

Now I just need to figure out why everything is populating as 0 bytes and 0 packets, I'll have to go head back to the troubleshooting page to see if this is referenced anywhere

![example4](https://github.com/user-attachments/assets/7cc32803-00b1-4254-afad-692e18ea1c73)

**Reply by fatherfbi** [reply]
> Thanks for the help with this, I've got at least the static interfaces showing as external now:
> 
> ![example3](https://private-user-images.githubusercontent.com/3943061/415378701-697d6738-0910-4554-b958-5f4bf3d47145.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAxMzEyNzcsIm5iZiI6MTc0MDEzMDk3NywicGF0aCI6Ii8zOTQzMDYxLzQxNTM3ODcwMS02OTdkNjczOC0wOTEwLTQ1NTQtYjk1OC01ZjRiZjNkNDcxNDUuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAyMjFUMDk0MjU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODQzNDVlZWYwZTczNGVmZThhY2M2M2E0YzBjMDg4YzU4NzRjMTEzNWY5NmU4MzRjMTA0YzAxOTQyZmE3OTQxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.NRxjMmi0Ii9oXjo2tA28zWGonH2YR84T1JZ8SJm-Tmc)
> 
> Now I just need to figure out why everything is populating as 0 bytes and 0 packets, I'll have to go head back to the troubleshooting page to see if this is referenced anywhere
> 
> ![example4](https://private-user-images.githubusercontent.com/3943061/415380054-7cc32803-00b1-4254-afad-692e18ea1c73.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAxMzEyNzcsIm5iZiI6MTc0MDEzMDk3NywicGF0aCI6Ii8zOTQzMDYxLzQxNTM4MDA1NC03Y2MzMjgwMy0wMGIxLTQyNTQtYWZhZC02OTJlMThlYTFjNzMuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAyMjFUMDk0MjU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDE2YTY2ODUwOWRkMDE5NDQ4MzAyNzgxMGJmOTZiNWRkNTQwOGFmNmY3NmM2YTY2YjUzNjQxYzRhZjgwZjVmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.MgqVNqaNv19XoESVdFDepKCZqH9O6Myax7dZShuP3B0)

Additional commands for debugging
```
curl -s http://127.0.0.1:8080/api/v0/inlet/metrics | grep '^akvorado_inlet' | grep _error
```
```
curl -s http://127.0.0.1:8080/api/v0/inlet/flows\?limit=1 | grep SamplingRate
```
```
curl -s http://127.0.0.1:8080/api/v0/inlet/metrics | grep '^akvorado_inlet_flow_input_udp_packets'
```
```
curl -s http://127.0.0.1:8080/api/v0/inlet/metrics | grep '^akvorado_inlet_kafka_sent_messages_total'
```

**Reply by resonator** [reply]
Unless I'm misinterpreting, it seems like the results of all these commands are good, here are my results:

curl -s http://127.0.0.1:8080/api/v0/inlet/metrics | grep '^akvorado_inlet' | grep _error 
- i have 16 flow_decoder_errors but they don't ever increase

curl -s http://127.0.0.1:8080/api/v0/inlet/flows\?limit=1 | grep SamplingRate
- this comes back as "SamplingRate": 1, which I have manually put in the inlet config

curl -s http://127.0.0.1:8080/api/v0/inlet/metrics | grep '^akvorado_inlet_flow_input_udp_packets'
- this is incrementing up slowly as (i think) is expected

curl -s http://127.0.0.1:8080/api/v0/inlet/metrics | grep '^akvorado_inlet_kafka_sent_messages_total'
- this is also incrementing up over time

**Comment by vincentbernat** [comment]
Can you provide the result of snmpwalk for ifName, ifAlias, and ifDescr?

**Reply by resonator** [reply]
Pasting the relevant interface results for each:

ifName:
IF-MIB::ifName.14 = STRING: Gi0/1

ifAlias: (this is what I want it to match on apparently)
IF-MIB::ifAlias.14 = STRING: Transit: Primary

ifDescr: (this is what I'm seeing in the "Last Flow" that isn't matching correctly)
IF-MIB::ifDescr.14 = STRING: GigabitEthernet0/1

**Reply by vincentbernat** [reply]
The current heuristic is to use ifDescr if different from ifName, and ifAlias otherwise. This is fixed in 798702b4c0aa.

**Reply by resonator** [reply]
Awesome that should solve my issue of the descriptions being pulled in incorrectly, should I open a new issue for my current issue of the packets and data being zero for all my flows? Or could this be possibly related?

![example4](https://github.com/user-attachments/assets/817c4449-a71c-49b1-ae50-d21dc7fe5671)

**Reply by vincentbernat** [reply]
No, for this, this is likely a problem with your exporter. Which OS is it running?

**Reply by resonator** [reply]
It is (unfortunately) an older version of cisco IOS ( Version 15.0(1r)M8 ), I don't control these boxes so I can't upgrade, I can only make changes to support the monitoring of them (like snmp, netflow etc..)

**Reply by fatherfbi** [reply]
> It is (unfortunately) an older version of cisco IOS ( Version 15.0(1r)M8 ), I don't control these boxes so I can't upgrade, I can only make changes to support the monitoring of them (like snmp, netflow etc..)

Write the model of your device and attach the netflow configuration

**Reply by vincentbernat** [reply]
I think you need to specifically enable counters: https://demo.akvorado.net/docs/operations#cisco-ios-xe

**Reply by resonator** [reply]
That did it! we're getting everything as expected now, I noticed that trying to add it fails if the netflow is in use on Cisco, I'm guessing that I attempted to add the collect counter statements as part of our new templates, but it was ignored since the flow record was already in use.

My fault on that, but we should be all good now, I'll just have to keep an eye out for that commit to make it to a release to fix the alias vs description issue. Thank you for all help

**Reply by vincentbernat** [reply]
In the meantime, you can replace the version of Akvorado in `docker/versions.yml` to `main`:
```yaml
  akvorado:
    image: ghcr.io/akvorado/akvorado:main
```

**Reply by bgkstl** [reply]
Hello Vincent, 
Bringing this one back up, I am on v1.11.3 running Cisco IOS XE Software, Version 17.16.01a. I am still seeing this behavior where the IntDescrip is simply the Interface name. I have edited the classifier to try to trick the system with no luck.  Any ideas on something more I can look into to resolve this.

```
core:
  default-sampling-rate: 100
  workers: 6
  exporter-classifiers:
    - ClassifySiteRegex(Exporter.Name, "^([^-]+)-", "$1")
    - ClassifyRegion("europe")
    - ClassifyTenant("acme")
    - ClassifyRole("edge")
  interface-classifiers:
    - |
      ClassifyConnectivityRegex(Interface.Description, "(labflow|.*ethernet.*)", "$0") &&
      ClassifyProviderRegex(Interface.Description, ".*", "$0") &&
      ClassifyExternal()
    - ClassifyInternal()

```


```
 curl -s http://127.0.0.1:8080/api/v0/inlet/flows\?limit=1 
{
    "TimeReceived": 1741365104,
    "SamplingRate": 100,
    "ExporterAddress": "::ffff:100.64.74.111",
    "InIf": 5,
    "OutIf": 16,
    "SrcVlan": 0,
    "DstVlan": 0,
    "SrcAddr": "::ffff:142.251.117.190",
    "DstAddr": "::ffff:172.22.100.10",
    "NextHop": "::ffff:172.22.100.10",
    "SrcAS": 0,
    "DstAS": 0,
    "GotASPath": false,
    "GotCommunities": false,
    "SrcNetMask": 0,
    "DstNetMask": 0
}

```
```
interface GigabitEthernet5
 description labflow
 ip flow monitor AkvoradoMonitor sampler random1in100 input
 ip flow monitor AkvoradoMonitor sampler random1in100 output
 ip address 10.11.1.11 255.255.255.0
 ip ospf network point-to-point
 ip ospf 100 area 0
 load-interval 30
 negotiation auto
end
```



![image](https://github.com/user-attachments/assets/098d2f32-d81a-4663-97c1-c9cd348b424e)
