### DISCUSSION TITLE
Service stops processing flow

### DISCUSSION THREAD

**Discussion by jakelty** [akvorado/akvorado#1684] [Q&A]
### Disclaimer

- [x] I have read and understood the disclaimer.

### Akvorado version

v1.11.3

### Bug description

I'm guessing this has to do with either Clickhouse of Kafka, but after some days or hours, the service will stop processing flow data properly. 

<img width="1982" alt="Image" src="https://github.com/user-attachments/assets/66ac0ca1-3e59-41da-97c7-8915efc2050b" />

<img width="1985" alt="Image" src="https://github.com/user-attachments/assets/99aa5d53-ece2-4fd4-82e9-4ae59f3f8398" />

However, I can see the flow data coming in
```
[root@netmon501 akvorado]# tcpdump -c 10 -ni enp1s0 port 2055
dropped privs to tcpdump
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on enp1s0, link-type EN10MB (Ethernet), capture size 262144 bytes
14:00:12.108142 IP 10.255.50.22.59763 > 10.55.200.110.iop: UDP, length 1340
14:00:12.108392 IP 10.255.50.22.59763 > 10.55.200.110.iop: UDP, length 1340
14:00:12.108625 IP 10.255.50.22.59763 > 10.55.200.110.iop: UDP, length 1340
14:00:12.108865 IP 10.255.50.22.59763 > 10.55.200.110.iop: UDP, length 1340
14:00:12.109117 IP 10.255.50.22.59763 > 10.55.200.110.iop: UDP, length 1340
14:00:12.109348 IP 10.255.50.22.59763 > 10.55.200.110.iop: UDP, length 1340
14:00:12.109609 IP 10.255.50.22.59763 > 10.55.200.110.iop: UDP, length 1340
14:00:12.109855 IP 10.255.50.22.59763 > 10.55.200.110.iop: UDP, length 1340
14:00:12.110088 IP 10.255.50.22.59763 > 10.55.200.110.iop: UDP, length 1340
14:00:12.110380 IP 10.255.50.22.59763 > 10.55.200.110.iop: UDP, length 1340
10 packets captured
68 packets received by filter
23 packets dropped by kernel
[root@netmon501 akvorado]#
```

akvorado.yaml

```
---
# This configuration file is documented in docs/02-configuration.md.
# You can get all default values with `akvorado orchestrator /dev/null
# --dump --check` or `docker compose run akvorado-orchestrator
# orchestrator /dev/null --dump --check`.

kafka:
  topic: flows
  version: 3.3.1
  brokers:
    - kafka:9092
  topic-configuration:
    num-partitions: 16
    replication-factor: 1
    config-entries:
      # The retention policy in Kafka is mainly here to keep a buffer
      # for ClickHouse.
      segment.bytes: 1073741824
      retention.ms: 86400000 # 1 day
      cleanup.policy: delete
      compression.type: producer

geoip:
  optional: true
  # When running on Docker, these paths are inside the container. By default,
  # IPinfo databases are used. (https://ipinfo.io/)
  asn-database:
    - /usr/share/GeoIP/asn.mmdb
  geo-database:
    - /usr/share/GeoIP/country.mmdb
  # If you want to use MaxmindDB, check `.env`, `docker-compose-maxmind.yml` and
  # update these paths:
  #asn-database:
  # - /usr/share/GeoIP/GeoLite2-ASN.mmdb
  #geo-database:
  # - /usr/share/GeoIP/GeoLite2-Country.mmdb

clickhouse:
  resolutions:
    - interval: 0
      ttl: 360h  # 15 days
    - interval: 1m
      ttl: 168h  # 1 week
    - interval: 5m
      ttl: 2160h # 3 months
    - interval: 1h
      ttl: 8760h
  orchestrator-url: http://akvorado-orchestrator:8080
  kafka:
    consumers: 4
  servers:
    - clickhouse:9000
  prometheus-endpoint: /metrics
  asns:
    64550: VA2
    64520: VA
    54243: Edge
  networks:
    # You should customize this section with your networks. This
    # populates the Src/DstNetName/Role/Site/Region/Tenant fields.
    10.20.0.0/24:
      name: internal_prod
      role: prod_va
      site: VA
      region: us-east
    10.20.1.0/24:
      name: internal_nonprod
      role: nonprod_va
      site: VA
      region: us-east
    10.255.50.0/24:
      name: vxlan_underlay
      role: prod_va2
      site: VA2
      region: us-east
    10.55.0.0/16:
      name: vxlan_prod
      role: prod_va2
      site: VA2
      region: us-east
    10.57.0.0/16:
      name: vxlan_stage
      role: stage_va2
      site: VA2
      region: us-east
    10.58.0.0/16:
      name: vxlan_storage
      role: storage
      site: VA2
      region: us-east
    66.59.82.0/24:
      name: va2_edge
      role: edge
      site: VA2
      region: us-east
    66.59.81.0/24:
      name: va_edge
      role: edge
      site: VA
      region: us-east
    66.59.83.0/24:
      name: col3_edge
      role: edge
      site: COL3
      region: us-east
  network-sources: []
    # amazon:
    #   url: https://ip-ranges.amazonaws.com/ip-ranges.json
    #   interval: 6h
    #   transform: |
    #     (.prefixes + .ipv6_prefixes)[] |
    #     { prefix: (.ip_prefix // .ipv6_prefix), tenant: "amazon", region: .region, role: .service|ascii_downcase }
    # gcp:
    #   url: https://www.gstatic.com/ipranges/cloud.json
    #   interval: 6h
    #   transform: |
    #     .prefixes[] |
    #     { prefix: (.ipv4Prefix // .ipv6Prefix), tenant: "google-cloud", region: .scope }

inlet: !include "inlet.yaml"
console: !include "console.yaml"

schema:
  materialize:
    - SrcNetPrefix
    - DstNetPrefix
  disabled:
    - ExporterTenant
    - DstNetTenant
    - SrcNetTenant
    - SrcNetRegion
    - DstNetRegion
  ```
