### DISCUSSION TITLE
Akvorado Widgets Not Showing

### DISCUSSION THREAD

**Discussion by uesturk** [akvorado/akvorado#1689] [Q&A] [answered]
Hello,
I installed it on docker by following the steps in the Akvorado document. And I can receive sflow traffic. The graphics and traffic are coming very clearly on the Visualize page. And I can analyze. But no data is coming on the Home page. What do I need to change about this? Can you help me visually? I would be very happy if you could explain visually where I need to change.

![image](https://github.com/user-attachments/assets/3f834bbb-69ed-4a23-932f-efff4200f724)

**Comment by fatherfbi** [comment]
> Hello, I installed it on docker by following the steps in the Akvorado document. And I can receive sflow traffic. The graphics and traffic are coming very clearly on the Visualize page. And I can analyze. But no data is coming on the Home page. What do I need to change about this? Can you help me visually? I would be very happy if you could explain visually where I need to change.
> 
> ![image](https://private-user-images.githubusercontent.com/202282900/420338715-3f834bbb-69ed-4a23-932f-efff4200f724.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEzNTI2NzcsIm5iZiI6MTc0MTM1MjM3NywicGF0aCI6Ii8yMDIyODI5MDAvNDIwMzM4NzE1LTNmODM0YmJiLTY5ZWQtNGEyMy05MzJmLWVmZmY0MjAwZjcyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwN1QxMjU5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODI5ZjhjMjllODJjNjY2MWJhZjY0YWJiZjFmNGNjOTQxYTRkNjY5NWE2NTg3NzhlNWNiMWEwNGViZDBjMzJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.a-IpHcozSPERzN7gi7X7AdnIIWyOEyXuwG7pjLI8hdY)

This is because your flows are not marked as Internal and External.

**Reply by uesturk** [reply]
How can I fix this? I can't see the screenshot you shared.

**Reply by fatherfbi** [reply]
> How can I fix this? I can't see the screenshot you shared.

https://demo.akvorado.net/docs/configuration#core

You need a section that starts with "Each Classify() function, with the exception of ClassifyExternal() and ClassifyInternal() have a variant ending with Regex which takes a string and a regex before the original string and do a regex match."

**Reply by uesturk** [reply]
I didn't understand exactly how to write it. If you are using akvorado, can you send the file content as an example?

**Reply by fatherfbi** [reply]
Write the name of the interface on which the flow is configured. And show your **inlet.yaml** configuration.

**Reply by uesturk** [reply]
My interface names come from a switch. One is inbound "1/0/11" and the other is outbound "2/0/11".

inlet.yaml , The contents are below.

sflowadmin@sflowadmin-virtual-machine:/akvorado/config$ cat inlet.yaml
---
kafka:
  compression-codec: zstd
metadata:
  workers: 10
  provider:
    type: snmp
    credentials:
      ::/0:
        communities: public
flow:
  inputs:
    - type: udp
      decoder: netflow
      listen: :2055
      workers: 6
      receive-buffer: 10485760
    - type: udp
      decoder: sflow
      listen: :6343
      workers: 6
      receive-buffer: 10485760
core:
  workers: 6
  exporter-classifiers:
    # This is an example. This should be customized depending on how
    # your exporters are named.
    - ClassifySiteRegex(Exporter.Name, "^([^-]+)-", "$1")
    - ClassifyRegion("europe")
    - ClassifyTenant("acme")
    - ClassifyRole("edge")
  interface-classifiers:
    # This is an example. This must be customized depending on the
    # descriptions of your interfaces. In the following, we assume
    # external interfaces are named "Transit: Cogent" Or "IX:
    # FranceIX".
    - |
      ClassifyConnectivityRegex(Interface.Description, "^(?i)(transit|pni|ppni|ix):? ", "$1") &&
      ClassifyProviderRegex(Interface.Description, "^\\S+?\\s(\\S+)", "$1") &&
      ClassifyExternal()
    - ClassifyInternal()

**Reply by fatherfbi** [reply]
> My interface names come from a switch. One is inbound "1/0/11" and the other is outbound "2/0/11".

Description?

**Reply by uesturk** [reply]
interface ethernet 1/0/11
 description IXIA-1_Port7_DOWNLOAD_TRAFFIC

interface ethernet 2/0/11
 description IXIA-1_Port8_UPLOAD_TRAFFIC

**Reply by fatherfbi** [reply]
There is an expression in the configuration.
```
ClassifyConnectivityRegex(Interface.Description, "^(?i)(transit|pni|ppni|ix):? ", "$1") &&
```
It is responsible for classifying external interfaces.

After it comes another expression that makes the classification of the provider.
```
ClassifyProviderRegex(Interface.Description, "^\S+?\s(\S+)", "$1") &&
```
Create a description of the ports on your switch and then they will be classified correctly.

interface ethernet 2/0/11
description IX: IXIA Port8_UPLOAD_TRAFFIC

Where **IX:** according to your configuration it will be marked as external and **IXIA** according to your configuration it will be marked as provider name  "IXIA"

**Reply by uesturk** [reply]
Frankly, I can't make it clear. Can you give me a configuration as an example?

**Reply by fatherfbi** [reply]
> interface ethernet 2/0/11
> description IX: IXIA Port8_UPLOAD_TRAFFIC

Change the port description on the switch to this
```
interface ethernet 2/0/11
description IX: IXIA Port8_UPLOAD_TRAFFIC
```

**Reply by uesturk** [reply]
Actually I want to explain it like this. Don't stick to the interface descriptions here. The IXIA is actually the name of the devices in the bypass module in my network structure. The important thing is that I receive download traffic from Ethernet1/0/11. I receive upload traffic from Ethernet2/0/11. I didn't know how to show these.

**Reply by uesturk** [reply]
Nothing changed. I did what you suggested but the widgets are not working.

![image](https://github.com/user-attachments/assets/6f5a6528-8dc2-44ab-aea1-66992e38c935)

**Comment by uesturk** [comment]
As you can see in the diagram, I am taking the traffic to the switch with a mirror. And I am sending it to Akvorado with sflow from the switch. The issue here is that in the bypass module, I can only take one direction of the telecom port coming to port A as a mirror. For this reason, in order to receive both download and upload traffic, I mirror both the in direction of port A (download) and the in direction of port B (upload). Therefore, the mirror traffic comes to the switch in the in direction. Akvorado cannot distinguish between both traffics since they come in the in direction. Can I show you which port is in and which port is out in Akvorado? I hope I was explanatory.


![image](https://github.com/user-attachments/assets/6b23da59-2575-4b8c-af18-f303302aa30a)

**Reply by uesturk** [reply]
@vincentbernat

**Comment by uesturk** [comment]
I have never done snmp configuration in akvorado. I have reviewed old conversations and documents a bit. I wanted to do the config. But I was not completely successful. There are some things I have paid attention to. I am pulling information from snmp with the default incoming public. But since the switch I am using is a d-link brand, I guess it cannot get the port description of the switch with the correct iod. The description it pulls includes things like the unit id and port number of the stack switch it is connected to. I am leaving the pcap in the attachment. You will see if you look. How can I pull the correct description? Can I change the oid or change the description with regex? Can you help me overcome this problem? @vincentbernat @fatherfbi
[snmpcap.zip](https://github.com/user-attachments/files/19159152/snmpcap.zip)

**Reply by fatherfbi** [reply]
Make a dump of your sflow and attach it here.

**Reply by uesturk** [reply]
sflow receiver 1 owner collector1 expiry infinite host 10.90.90.89
!
interface ethernet 1/0/11
 description IXIA-1_Port7_DOWNLOAD_TRAFFIC
 max-rcv-frame-size 12288
 transceiver-monitoring enable
 sflow sampler 1 receiver 1 sampling-rate 1 max-header-size 256
 sflow poller 1 receiver 1 interval 30
!
interface ethernet 2/0/11
 description ix: IXIA-1_Port8_UPLOAD_TRAFFIC
 max-rcv-frame-size 12288
 transceiver-monitoring enable
 sflow sampler 1 receiver 1 sampling-rate 1 max-header-size 256
 sflow poller 1 receiver 1 interval 30
!
interface ethernet 1/0/2
 description AKVORADO
 max-rcv-frame-size 12288
 transceiver-monitoring enable
 switchport mode access
 switchport access vlan 12

**Reply by fatherfbi** [reply]
I'm talking about traffic dump using tcpdump or wireshark.

**Reply by uesturk** [reply]
Of course I'm adding that too

[sflow.zip](https://github.com/user-attachments/files/19160881/sflow.zip)

**Reply by uesturk** [reply]
Have you reviewed it?

**Reply by uesturk** [reply]
@fatherfbi ?

**Reply by uesturk** [reply]
I think this problem is difficult for you too. @fatherfbi

**Reply by fatherfbi** [reply, marked as answer]
> I think this problem is difficult for you too. @fatherfbi

Try setting up a **static provider**. Then you will understand what your problem is and how to classify the streams correctly.

Configuration example
inlet.yaml
```
---
kafka:
  compression-codec: zstd
metadata:
  workers: 20
  providers:
    - type: static
      exporters:
        10.255.255.1:
          name: SWITCH2
          default:
            name: unknown
            description: Unknown interface
            speed: 100
          ifindexes:
            369098753:
              name: PortChannel2
              description: UPL APPLE
              speed: 20000
            369098761:
              name: PortChannel10
              description: UPL META
              speed: 80000
    - type: snmp
      communities:
        10.255.255.1: "1qazxsw2"
flow:
  inputs:
    - type: udp
      decoder: netflow
      listen: :2055
      workers: 20
      receive-buffer: 10485760
    - type: udp
      decoder: sflow
      listen: :6343
      workers: 20
      receive-buffer: 10485760
routing:
  provider:
    type: bmp
    listen: 0.0.0.0:10179
    collect-asns: true
    collect-aspaths: true
    collect-communities: true
core:
  workers: 20
  default-sampling-rate: 1
  interface-classifiers:
    - |
      ClassifyConnectivityRegex(Interface.Description, "^(?i)(upl|pni|ix):? ", "$1") &&
      ClassifyProviderRegex(Interface.Description, "^\\S+?\\s(\\S+)", "$1") &&
      ClassifyExternal()
    - ClassifyInternal()

```
