### DISCUSSION TITLE
I can't see flows coming to my server

### DISCUSSION THREAD

**Discussion by dannyxyz** [akvorado/akvorado#1707] [Q&A]
I see this error when i run the command:

curl -s http://127.0.0.1:8080/api/v0/inlet/metrics | grep '^akvorado_inlet' | grep core

akvorado_inlet_core_classifier_exporter_cache_size_items 0
akvorado_inlet_core_classifier_interface_cache_size_items 0
akvorado_inlet_core_flows_errors_total{error="SNMP cache miss",exporter="154.66.247.23"} 6.398543e+07
akvorado_inlet_core_flows_errors_total{error="SNMP cache miss",exporter="154.66.247.30"} 1.374188039e+09
akvorado_inlet_core_flows_errors_total{error="sampling rate missing",exporter="154.66.247.30"} 1.601663e+06
akvorado_inlet_core_flows_http_clients 0
akvorado_inlet_core_received_flows_total{exporter="154.66.247.23"} 6.398543e+07
akvorado_inlet_core_received_flows_total{exporter="154.66.247.30"} 1.374188039e+09

what could be the issue

**Comment by dannyxyz** [comment]
Please i need help setting this up. i am at a wits end:

akvorado_inlet_core_flows_errors_total{error="SNMP cache miss",exporter="154.66.247.30"} 1
akvorado_inlet_core_flows_errors_total{error="sampling rate missing",exporter="154.66.247.30"} 608679
akvorado_inlet_flow_decoder_errors_total{name="netflow"} 139140
akvorado_inlet_metadata_provider_snmp_poller_error_requests_total{error="get",exporter="154.66.247.30"} 1

THis is my inlet file:

---
kafka:
  compression-codec: zstd
metadata:
  workers: 16
  provider:
    type: snmp
    credentials:
      ::/0:
        communities: "W10cc2014"
flow:
  inputs:
    - type: udp
      decoder: ipfix
      listen: :2055
      workers: 6
      receive-buffer: 33554432
    - type: udp
      decoder: sflow
      listen: :6343
      workers: 6
      receive-buffer: 10485760
core:
  workers: 16
  override-sampling-rate: 1024
  exporter-overrides:
    "154.66.247.30":
      sampling-rate: 1024
      decoder: ipfix
  exporter-classifiers:
    # This is an example. This should be customized depending on how
    # your exporters are named.
    - ClassifySiteRegex(Exporter.Name, "^([^-]+)-", "$1")
    - ClassifyRegion("europe")
    - ClassifyTenant("acme")
    - ClassifyRole("edge")
  interface-classifiers:
    # This is an example. This must be customized depending on the
    # descriptions of your interfaces. In the following, we assume
    # external interfaces are named "Transit: Cogent" Or "IX:
    # FranceIX".
    - |
      ClassifyConnectivityRegex(Interface.Description, "^(?i)(transit|pni|ppni|ix):? ", "$1") &&
      ClassifyProviderRegex(Interface.Description, "^\\S+?\\s(\\S+)", "$1") &&
      ClassifyExternal()
    - ClassifyInternal()

I just don't know what else to do:
![akvorado_1](https://github.com/user-attachments/assets/5a6cb5be-1647-4833-9dac-989182a859cc)

**Comment by fatherfbi** [comment]
Hi dannyxyz
Error "SNMP cache miss" says that Akvorado can't query the device 154.66.247.23
Error "sampling rate missing" says the device 154.66.247.30 don't say flow rate.
And your interfaces are not classified.

P.S. Please insert the code through triple grave accent in the future
Example
```
kafka:
  compression-codec: zstd
metadata:
  workers: 16
  provider:
  type: snmp
    credentials:
    : :/0:
     communities: "W10cc2014"
flow:
  inputs:
    - type: udp
       decoder: ipfix
       listen: :2055
       workers: 6
       receive-buffer: 33554432
       - type: udp
       decoder: sflow
        listen: :6343
       workers: 6
       receive-buffer: 10485760
```
![image](https://github.com/user-attachments/assets/6568e31d-ed63-4dc0-a502-62992331c8d8)

**Reply by LoveSkylark** [reply]
Had a similar issue fixed  "docker compose up --force-recreate -d"
seems that if you start the container with the default "public"  it does not change went you restart the container normally.

**Reply by chupztugz000000000** [reply]
how do you setup if you have snmpv3

**Comment by roopeshsn** [comment]
@fatherfbi I see from the Quick start documentation, the outlet fields should be modified.

<img width="1250" height="761" alt="Screenshot 2025-08-06 at 5 13 38 PM" src="https://github.com/user-attachments/assets/3988b722-8ffa-4d87-b592-59aac5785331" />


I created `outlet.yaml` file and added the below contents:

```
metadata:
  workers: 10
  providers:
    type: snmp
    credentials:
      ::/0:
        communities:
          - public

core:
  interface-classifiers:
    - |
      ClassifyConnectivityRegex(Interface.Description, "^(?i)(transit|pni|ppni|ix):? ", "$1") &&
      ClassifyProviderRegex(Interface.Description, "^[^ ]+? ([^ ]+)", "$1") &&
      ClassifyExternal()    
    - ClassifyInternal()
  exporter-classifiers:
    - ClassifySiteRegex(Exporter.Name, "^([^-]+)-", "$1")
    - Exporter.Name endsWith ".it" && ClassifyRegion("italy")
    - Exporter.Name matches "^(washington|newyork).*" && ClassifyRegion("usa")
    - Exporter.Name endsWith ".fr" && ClassifyRegion("france")
```

Also I updated the `akvorado.yaml` file with the below line pointing to the file like inlet and console.

```
outlet: !include "outlet.yaml"
```

After the above changes, when I ran the "docker compose up" command, I see the below error:

```
...
clickhouse-1                | Downloading ClickHouse init script...
clickhouse-1                | Downloading ClickHouse init script...
akvorado-orchestrator-1     | Error: invalid configuration:
akvorado-orchestrator-1     | invalid key "outlet"
clickhouse-1                | Downloading ClickHouse init script...
akvorado-orchestrator-1 exited with code 1
...
```

The outlet changes are not required?
