### DISCUSSION TITLE
INLET kafka SASL/OAUTHBEARER saslmechanism

### DISCUSSION THREAD

**Discussion by vseregin63** [akvorado/akvorado#1714] [Q&A]
Have a good day, @vincentbernat

Where are centralized installations of ClickHouse and Kafka in our company and we want to use just Inlet and console modules without orchestrator service. In discussions https://github.com/akvorado/akvorado/discussions/58 and https://github.com/akvorado/akvorado/discussions/1685 You confirmed that we can do it. At this point we can run inlet module separately and successfully write messages to kafka with Plaintext auth method.
But we have a trouble - kafka brokers in our prod evironment supports only sasl/oauthbearer auth method. 
In such case we need to provide additionally url to get JWM token and saslmechanism must be set to OAUTHBEARER. Below example from another product 

```yaml
  kafka:
    sasl:
      user: "user"
      password: "passw"
      mechanism: OAUTHBEARER
      token-url: https://example.com/auth/realms/protocol/openid-connect/token
```

Akvorado support such sasl auth mechanism ? If NO, can we make request to add this functionality to it?

Thanks!

**Comment by vincentbernat** [comment]
It is currently not supported, but it looks like it could be supported easily.

**Comment by vseregin63** [comment]
@vincentbernat Is it possible to add support to next release ?

**Reply by vincentbernat** [reply]
When looking a bit, this does not seem to be really universal. There are several ways to get tokens. Which product do you refer to in your example so that I can look in the documentation all the methods implemented?

**Reply by vseregin63** [reply]
As i understood where are several auth mechanisms supported in kafka:

**Plaintext** – no auth
**SaslPlaintext** – auth by login/passw
**SaslScramSHA256(512)** - auth by login/salted_password
**SaslTypeOAuth** - auth via jwt token got from OIDC provider
**SaslGSSAPI** - auth via LDAP

If we need we can add TLS cipher to these types and got an additional protection.

Current inlet kafka configuration has structure

```
kafka:
    topic: [topic_name]
    brokers:
        - [kafka_broker]:[port]
    version: [2.7.0]
    tls:
        enable: true
        verify: false
        cafile: ""
        certfile: ""
        keyfile: ""
        saslusername: [username]
        saslpassword: [password]
        saslmechanism: [SASL.Mechanism]
    flushinterval: 1s
    flushbytes: 104857599
    maxmessagebytes: 1000000
    compressioncodec: zstd
    queuesize: 32
```

My suggestion about SASL parameters - they should be grouped separately like below, because tls is not necessary, it can be applied or not. In current structure we can't config connection without tls applied.

```
kafka:
    tls:
        enable: true
        verify: false
        cafile: ""
        certfile: ""
        keyfile: ""
    sasl:
        saslmechanism: [SASL.Mechanism]
        saslusername: [username]
        saslpassword: [password]
```

I got a needed to me behaviour by appending to your code
```
akvorado/common/kafka/config.go
const (
       ...	
        // SASLTypeOAuth enables OAUTH via OIDC provider
	SASLTypeOAuth
)
func NewConfig(config Configuration) (*sarama.Config, error) {
        ...
	if tlsConfig != nil {
                ...
		if config.TLS.SASLUsername != "" {
                         ...
			if config.TLS.SASLMechanism == SASLTypeOAuth {
				kafkaConfig.Net.SASL.Mechanism = sarama.SASLTypeOAuth
				kafkaConfig.Net.SASL.TokenProvider = pkgutils.NewTokenProvider(config.TLS.SASLUsername, config.TLS.SASLPassword, config.TLS.TokenURL)
				kafkaConfig.Net.SASL.Version = 1
				kafkaConfig.Net.SASL.Handshake = true
			}
		}
	}

added file akvorado/common/utils/authbrearer.go 
...
// TokenProvider is a simple struct that implements sarama.AccessTokenProvider.
type TokenProvider struct {
	tokenSource oauth2.TokenSource
}
func NewTokenProvider(clientID, clientSecret, tokenURL string) sarama.AccessTokenProvider {
	cfg := clientcredentials.Config{
		ClientID:     clientID,
		ClientSecret: clientSecret,
		TokenURL:     tokenURL,
	}

	return &TokenProvider{
		tokenSource: cfg.TokenSource(context.Background()),
	}
}
```

Appended kafka inlet config:
```
kafka:
    topic: akvorado-inlet
    brokers:
        - [kafka_broker]:[port]
    version: 2.7.0
    tls:
        enable: true
        verify: false
        saslusername: [username]
        saslpassword: [password]
        saslmechanism: 4
        tokenurl: [url to oidc provider api]
    flushinterval: 1s
    flushbytes: 104857599
    maxmessagebytes: 1000000
    compressioncodec: zstd
    queuesize: 32

```
