### DISCUSSION TITLE
Reported traffic seems to half after ~4-5 minutes of uptime

### DISCUSSION THREAD

**Discussion by nzurku** [akvorado/akvorado#1722] [Q&A]
<img width="1604" alt="Screenshot 2025-04-14 at 5 18 38 PM" src="https://github.com/user-attachments/assets/bdb047a7-e50c-48bc-a76d-e67ef0e8f611" />

Not sure where to look for this one, we've done a lot of tuning to handle our traffic and things do work great with keeping up... But we seem to have a 50% traffic rate drop after ~3 minutes of uptime.

Reported sample rates appear to be correct. All routers are pushing 1024, and the default sample rate is also set to 1024. Restarting the containers resolves the issue until the next ~3 minutes.

Once the traffic is "half" it will run forever and is accurate except you would just need to double the values. No flows appear to be missing, all routers and interfaces are accounted for. A maxed out 100g port will simply report as 50gbps of traffic.

Is there something that happens a bit after start-up with changing how sampling rates are handled?

**Comment by fatherfbi** [comment]
What is your volume Flows/s?
How many network interfaces do you have?
Show the Core section from the inlet config.
```
core:
  workers: 20
  default-sampling-rate: 1
  interface-classifiers:
    - |
      ClassifyConnectivityRegex(Interface.Description, "^(?i)(upl|pni|ix):? ", "$1") &&
      ClassifyProviderRegex(Interface.Description, "^\\S+?\\s(\\S+)", "$1") &&
      ClassifyExternal()
    - ClassifyInternal()
   ```

**Comment by nzurku** [comment]
```
core:
  default-sampling-rate: 1024
  workers: 32
  exporter-classifiers:
    - ClassifySiteRegex(Exporter.Name, '^[^.]+[.]([^.]+)[.]', '$1')
    - Exporter.Name startsWith "er" && ClassifyRole("edge")
    - Exporter.Name startsWith "sp" && ClassifyRole("spine")
    - Exporter.Name startsWith "lf" && ClassifyRole("leaf")
  interface-classifiers:
    - |
      ClassifyConnectivityRegex(Interface.Description, '^(?i)(transit|pni|ppni|peering):? ', '$1') &&
      ClassifyProviderRegex(Interface.Description, '^[^ ]+: [^ ]+ ([^ ]+)', '$1') && ClassifyExternal()
    - ClassifyInternal()
```

Akvorado is currently reporting 68.6K Flows/s which stays the same even if we're in early start up or after the decrease happens.

I would estimate less than 500 interfaces are involved in these edge devices.

**Reply by fatherfbi** [reply]
> ```
> core:
>   default-sampling-rate: 1024
>   workers: 32
>   exporter-classifiers:
>     - ClassifySiteRegex(Exporter.Name, '^[^.]+[.]([^.]+)[.]', '$1')
>     - Exporter.Name startsWith "er" && ClassifyRole("edge")
>     - Exporter.Name startsWith "sp" && ClassifyRole("spine")
>     - Exporter.Name startsWith "lf" && ClassifyRole("leaf")
>   interface-classifiers:
>     - |
>       ClassifyConnectivityRegex(Interface.Description, '^(?i)(transit|pni|ppni|peering):? ', '$1') &&
>       ClassifyProviderRegex(Interface.Description, '^[^ ]+: [^ ]+ ([^ ]+)', '$1') && ClassifyExternal()
>     - ClassifyInternal()
> ```
> 
> Akvorado is currently reporting 68.6K Flows/s which stays the same even if we're in early start up or after the decrease happens.
> 
> I would estimate less than 500 interfaces are involved in these edge devices.

Most likely, you have encountered a problem that I once encountered.

https://github.com/akvorado/akvorado/discussions/1574

**Reply by nzurku** [reply]
```
core:
  default-sampling-rate: 1024
  workers: 32
  exporter-classifiers:
    - ClassifySiteRegex(Exporter.Name, '^[^.]+[.]([^.]+)[.]', '$1')
#    - Exporter.Name startsWith "er" && ClassifyRole("edge")
#    - Exporter.Name startsWith "sp" && ClassifyRole("spine")
#    - Exporter.Name startsWith "lf" && ClassifyRole("leaf")
  interface-classifiers:
    - |
      ClassifyConnectivityRegex(Interface.Description, '^(?i)(transit|pni|ppni|peering):? ', '$1') &&
      ClassifyExternal()
#      ClassifyProviderRegex(Interface.Description, '^[^ ]+: [^ ]+ ([^ ]+)', '$1') && ClassifyExternal()
    - ClassifyInternal()
```

I chopped out a good bit of the regex other than some bare minimum and it's still breaking.

I'll likely need to install that Go Profiler stuff and see if these remaining lines are breaking it.

Thanks for the lead.
