### DISCUSSION TITLE
Inlet Stops Collecting Flows When Querying Historical Data

### DISCUSSION THREAD

**Discussion by khusleek** [akvorado/akvorado#1726] [Q&A]
Hello,
In my case, the inlet receives 20,000 flows per second during peak times, with a sampling rate of 100. I was running v1.11.2, and my resolution configuration was as follows:
```
resolutions:
  - interval: 0s
    ttl: 744h0m0s
  - interval: 5m0s
    ttl: 2160h0m0s
  - interval: 1h0m0s
    ttl: 8640h0m0s
```
Everything was running normally until one day, the disk ran out of space.

After that, I took the following steps:
1. Dropped the flows and flows_5m tables.
2. Upgraded Akvorado to v1.11.3.
3. Updated the resolution configuration to:
```
resolutions:
  - interval: 0s
    ttl: 48h0m0s
  - interval: 1m0s
    ttl: 840h0m0s
  - interval: 5m0s
    ttl: 2160h0m0s
  - interval: 1h0m0s
    ttl: 8760h0m0s
```
4. Modified the schema to store SrcAddr and DstAddr in a non-main table.
```
schema:
  not-main-table-only:
    - SrcAddr
    - DstAddr
```
After these changes, SrcAddr and DstAddr are available in flows_1m0s for the last 4 days of flows. However, when I query data for the last 2 days or more, the inlet stops collecting flows, as shown in the screenshots.
![akvorado](https://github.com/user-attachments/assets/37120365-c3bc-471d-8f02-b31b1ba23d35)

As part of troubleshooting, I also:
 - Increased the number of workers for the core module.
 - Increased the number of Kafka partitions, as recommended in the documentation.
Despite all these adjustments, the issue still persists. 
Any insights or recommendations to help resolve this would be greatly appreciated.
