### DISCUSSION TITLE
Inlet and Kafka get data, Web UI does not.

### DISCUSSION THREAD

**Discussion by techyporcupine** [akvorado/akvorado#1740] [Q&A]
Hello! I am trying to set up Akvorado on a NixOS system. It uses the flake.nix provided in this repo to build from source, and I have Clickhouse and Kafka enabled separately in NixOS. All 3 components of Akvorado will run, but the Web UI reports "0 Flows/s". I can see Kafka gets flow data, but I don't know where it goes from there. Help would be much appreciated! I'm running everything that would have been on port 8080 instead on 8083 as my Unifi Controller (hosted on the same machine) needs that port for device comms. I can tell the WebUI is also connecting to Clickhouse as if I change the port to something that doesn't have clickhouse behind it, it says something like "N/A" instead of "0 Flows/s". My theory is a breakdown between Kafka and Clickhouse, but I also do not understand how the underlying layers of this application work, so I may be totally wrong.

These are the commands being run for each Akvorado component:
`akvorado --debug inlet http://127.0.0.1:8083`
`akvorado --debug orchestrator /var/lib/akvorado-orchestrator/config.yaml`
`akvorado --debug console http://127.0.0.1:8083`

Config:

```
---
reporting:
    logging: {}
    metrics: {}

http:
    listen: :8083
    profiler: true
    cache:
        type: memory

kafka:
    topic: flows
    brokers:
        - 127.0.0.1:9092
    version: 5.3.0
    topic-configuration:
        num-partitions: 1
        replication-factor: 1
        config-entries:
          segment.bytes: 1073741824
          retention.ms: 86400000 # 1 day
          cleanup.policy: delete
          compression.type: producer

geoip:
    asn-database: /var/lib/akvorado-orchestrator/GeoLite2-ASN.mmdb
    geo-database: /var/lib/akvorado-orchestrator/GeoLite2-Country.mmdb

clickhouse:
    servers:
        - 127.0.0.1:9000
    kafka:
        consumers: 4
    networks:
      10.0.0.0/24:
        name: Management
        role: Management
    network-sources: []
    orchestrator-url: http://127.0.0.1:8083

inlet:
    - reporting:
        logging: {}
        metrics: {}
      http:
        listen: :8081
        profiler: true
        cache:
            type: memory
      kafka:
        compression-codec: none
      metadata:
        workers: 5
        providers:
              type: snmp
              securityparameters:
                username: opnsense
                authentication-protocol: sha
                authentication-passphrase: '--'
                privacy-protocol: aes
                privacy-passphrase: '--'
      flow:
        inputs:
        - type: udp
          decoder: netflow
          listen: :2055
          workers: 5
          use-src-addr-for-exporter-addr: true
      core:
        workers: 5
        exporter-classifiers: []
        interface-classifiers:
        - ClassifyExternal()
        - ClassifyInternal()
        default-sampling-rate: 1

console:
    - reporting:
        logging: {}
        metrics: {}
      http:
        listen: :8082
        profiler: true
        cache:
            type: memory
      default-visualize-options:
        graphtype: stacked
        start: 12 hours ago
        end: now
        filter: ''
        dimensions:
            - ExporterName
            - SrcAddr
            - DstAddr
        limit: 10
        bidirectional: false
        previousperiod: false
      homepage-top-widgets:
        - src-as
        - src-port
        - protocol
        - etype
      homepage-graph-filter: ''
      clickhouse:
        servers:
            - 127.0.0.1:9000
        database: default
        username: default
      auth:
        headers:
            login: Remote-User
            name: Remote-Name
            email: Remote-Email
            logouturl: X-Logout-URL
        defaultuser:
            login: __default
            name: Default User
            email: ""
            logouturl: ""
```
