### DISCUSSION TITLE
Limit Rate - Filter

### DISCUSSION THREAD

**Discussion by theangelz** [akvorado/akvorado#1757] [Q&A]
When creating the filter, I get a limited list of a maximum of 50 items.
The rest goes to someone else. How can I increase this to 100 items?
![image](https://github.com/user-attachments/assets/0ab0343f-2643-4d19-90e6-ed1b035581e8)
as in the photo, see limit 50, and the graph remains gray still missing a list

**Comment by fatherfbi** [comment]
console.yaml
```
---
http:
  cache:
    type: redis
    server: redis:6379
default-visualize-options:
  graph-type: stacked
  start: 6 hours ago
  end: now
  filter: InIfBoundary = external
  dimensions:
      - ExporterName
  limit: 10
homepage-top-widgets:
  - src-as
  - dst-as
  - protocol
  - dst-port
  - etype
dimensions-limit: 100
```
