### DISCUSSION TITLE
Missing "Top Protocols" and "IPv4/IPv6" Data in Akvorado Dashboard

### DISCUSSION THREAD

**Discussion by Martin22** [akvorado/akvorado#1774] [Q&A]
### Disclaimer

- [x] I have read and understood the disclaimer.

### Akvorado version

akvorado v1.11.5   Built with: go1.24.2

### Bug description

The Akvorado dashboard is not displaying data in the Top Protocols and IPv4/IPv6 sections. Both charts appear empty and only show "Others", with no further breakdown or useful information.

Interestingly, these statistics briefly appeared during the day yesterday, but they are no longer visible now.

![Image](https://github.com/user-attachments/assets/b1f20607-d2ad-46de-b300-8a6d09849740)

Please investigate and advise. Thanks!

**Comment by vincentbernat** [comment]
Direction-independent information are fetched using OutIfBoundary = 'external'. If you don't classify output interfaces correctly, you'll get that.

**Reply by Martin22** [reply]
Thank you for your response.

All my external interfaces are correctly classified – each one has transit or peering specified in the description. I have also properly adjusted the corresponding regular expression in the configuration. All other interfaces are internal.

If more detailed information is needed to identify what might be wrong, please let me know what exactly to check or provide.

Thank you.

**Reply by vincentbernat** [reply]
Do a query with `OutIfBoundary = external`. I think it will return nothing.

**Comment by morhold** [comment]
Can you tell me what type of flow you use?  We had a similar experience when using imon (ipfix315). Since it was simple at the test level, we did not investigate the problem in depth.
At the same time, if you look in visualize - protocols and other information were displayed correctly.

**Reply by Martin22** [reply]
I am using Cisco ASR 9001 with NetFlow v9 and BMP enabled.

**Comment by shotarry26** [comment]
@vincentbernat 

If my interfaces are all internal, I wouldn't get data from those widgets?

OutIfBoundary = external and InIfBoundary = external, both return empty.

How and where can I classify interfaces?

**Reply by chupztugz000000000** [reply]
` # Classifiers for interfaces based on name and description.
  interface-classifiers:
    # Match external interfaces such as Transit, PNI, PPNI, or IX.
    # Example: "Transit: Cogent" -> Connectivity: Transit, Provider: Cogent.
    - |
      ClassifyConnectivityRegex(Interface.Description, '^(?i)(transit|pni|ppni|ix):? ', '$1') &&
      ClassifyProviderRegex(Interface.Description, '^\\S+?\\s(\\S+)', '$1') &&
      ClassifyExternal()

    # Match point-to-point (P2P) links.
    # Example: "p2p link to 10.9" -> Connectivity: p2p, External.
    - |
      ClassifyConnectivityRegex(Interface.Description, '(?i)ge-', 'ge') &&
      ClassifyExternal()
    - |
      ClassifyConnectivityRegex(Interface.Description, '(?i)p2p', 'p2p') &&
      ClassifyExternal()

    # Match GRE interfaces by interface name (e.g., "gr-0/0/0.40").
    # Mark them as GRE connectivity and Internal.
    - |
      ClassifyConnectivityRegex(Interface.Name, '^(?i)gr-', 'GRE') &&
      ClassifyInternal()

    # Default classification for other internal interfaces.
    - ClassifyInternal()` --- can someone help me? because even i had the interface in Ge-0-1 for WAN interface still its getting to internal traffic

**Reply by fatherfbi** [reply]
> ` # Classifiers for interfaces based on name and description. interface-classifiers: # Match external interfaces such as Transit, PNI, PPNI, or IX. # Example: "Transit: Cogent" -> Connectivity: Transit, Provider: Cogent. - | ClassifyConnectivityRegex(Interface.Description, '^(?i)(transit|pni|ppni|ix):? ', '$1') && ClassifyProviderRegex(Interface.Description, '^\S+?\s(\S+)', '$1') && ClassifyExternal()
> 
> ```
> # Match point-to-point (P2P) links.
> # Example: "p2p link to 10.9" -> Connectivity: p2p, External.
> - |
>   ClassifyConnectivityRegex(Interface.Description, '(?i)ge-', 'ge') &&
>   ClassifyExternal()
> - |
>   ClassifyConnectivityRegex(Interface.Description, '(?i)p2p', 'p2p') &&
>   ClassifyExternal()
> 
> # Match GRE interfaces by interface name (e.g., "gr-0/0/0.40").
> # Mark them as GRE connectivity and Internal.
> - |
>   ClassifyConnectivityRegex(Interface.Name, '^(?i)gr-', 'GRE') &&
>   ClassifyInternal()
> 
> # Default classification for other internal interfaces.
> - ClassifyInternal()` --- can someone help me? because even i had the interface in Ge-0-1 for WAN interface still its getting to internal traffic
> ```
Your config is not entirely clear, could you attach the entire contents of the inlet.yaml file?

**Reply by chupztugz000000000** [reply]
This is my inlet.yaml file! @fatherfbi  Im only getting all internal traffic
`---
kafka:
  compression-codec: zstd

metadata:
  workers: 10
  providers:
    - type: snmp
      credentials:
        "::/0":
            user-name: xxxx
            authentication-protocol: SHA
            authentication-passphrase: xxxxx
            privacy-protocol: DES
            privacy-passphrase: xxxxxxx
      poller-retries: 10
      poller-timeout: 30s

flow:
  inputs:
    - type: udp
      decoder: netflow
      listen: :9996
      workers: 6
      receive-buffer: 10485760
    - type: udp
      decoder: sflow
      listen: :6343
      workers: 6
      receive-buffer: 10485760

core:
  # Number of worker threads for processing flows.
  # Adjust based on the number of CPU cores available.
  default-sampling-rate: 20
  workers: 6

  # Classifiers for exporters (devices sending flows).
  exporter-classifiers:
    # Extract site from exporter name before the first '-'.
    # Example: "NYC-FW1" -> Site: "NYC".
    - ClassifySiteRegex(Exporter.Name, '^([^-]+)-', '$1')

    # Hardcode region, tenant, and role.
    - ClassifyRegion('xxxx')
    - ClassifyTenant('xxxx')
    - ClassifyRole('xxxxxl')

  # Classifiers for interfaces based on name and description.
  interface-classifiers:
    # Match external interfaces such as Transit, PNI, PPNI, or IX.
    # Example: "Transit: Cogent" -> Connectivity: Transit, Provider: Cogent.
    - |
      ClassifyConnectivityRegex(Interface.Description, '^(?i)(transit|pni|ppni|ix):? ', '$1') &&
      ClassifyProviderRegex(Interface.Description, '^\\S+?\\s(\\S+)', '$1') &&
      ClassifyExternal()

    # Match point-to-point (P2P) links.
    # Example: "p2p link to 10.9" -> Connectivity: p2p, External.
    - |
      ClassifyConnectivityRegex(Interface.Description, '(?i)ge-', 'ge') &&
      ClassifyExternal()
    - |
      ClassifyConnectivityRegex(Interface.Description, '(?i)p2p', 'p2p') &&
      ClassifyExternal()

    # Match GRE interfaces by interface name (e.g., "gr-0/0/0.40").
    # Mark them as GRE connectivity and Internal.
    - |
      ClassifyConnectivityRegex(Interface.Name, '^(?i)gr-', 'GRE') &&
      ClassifyInternal()

    # Default classification for other internal interfaces.
    - ClassifyInternal()`

**Reply by fatherfbi** [reply]
> This is my inlet.yaml file! @fatherfbi Im only getting all internal traffic `--- kafka: compression-codec: zstd
> 
> metadata: workers: 10 providers: - type: snmp credentials: "::/0": user-name: xxxx authentication-protocol: SHA authentication-passphrase: xxxxx privacy-protocol: DES privacy-passphrase: xxxxxxx poller-retries: 10 poller-timeout: 30s
> 
> flow: inputs: - type: udp decoder: netflow listen: :9996 workers: 6 receive-buffer: 10485760 - type: udp decoder: sflow listen: :6343 workers: 6 receive-buffer: 10485760
> 
> core:
> 
> # Number of worker threads for processing flows.
> # Adjust based on the number of CPU cores available.
> default-sampling-rate: 20 workers: 6
> 
> # Classifiers for exporters (devices sending flows).
> exporter-classifiers: # Extract site from exporter name before the first '-'. # Example: "NYC-FW1" -> Site: "NYC". - ClassifySiteRegex(Exporter.Name, '^([^-]+)-', '$1')
> 
> ```
> # Hardcode region, tenant, and role.
> - ClassifyRegion('xxxx')
> - ClassifyTenant('xxxx')
> - ClassifyRole('xxxxxl')
> ```
> 
> # Classifiers for interfaces based on name and description.
> interface-classifiers: # Match external interfaces such as Transit, PNI, PPNI, or IX. # Example: "Transit: Cogent" -> Connectivity: Transit, Provider: Cogent. - | ClassifyConnectivityRegex(Interface.Description, '^(?i)(transit|pni|ppni|ix):? ', '$1') && ClassifyProviderRegex(Interface.Description, '^\S+?\s(\S+)', '$1') && ClassifyExternal()
> 
> ```
> # Match point-to-point (P2P) links.
> # Example: "p2p link to 10.9" -> Connectivity: p2p, External.
> - |
>   ClassifyConnectivityRegex(Interface.Description, '(?i)ge-', 'ge') &&
>   ClassifyExternal()
> - |
>   ClassifyConnectivityRegex(Interface.Description, '(?i)p2p', 'p2p') &&
>   ClassifyExternal()
> 
> # Match GRE interfaces by interface name (e.g., "gr-0/0/0.40").
> # Mark them as GRE connectivity and Internal.
> - |
>   ClassifyConnectivityRegex(Interface.Name, '^(?i)gr-', 'GRE') &&
>   ClassifyInternal()
> 
> # Default classification for other internal interfaces.
> - ClassifyInternal()`   
> ```

Please paste the file contents as code so it is easy to read.
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks

**Comment by chupztugz000000000** [comment]
```
`---`
kafka:
  compression-codec: zstd

metadata:
  workers: 10
  providers:
    - type: snmp
      credentials:
        "::/0":
            user-name: Usymv3
            authentication-protocol: SHA
            authentication-passphrase: M0n1t0r1ng!
            privacy-protocol: DES
            privacy-passphrase: M0n1t0r1ng!
      poller-retries: 10
      poller-timeout: 30s

flow:
  inputs:
    - type: udp
      decoder: netflow
      listen: :9996
      workers: 6
      receive-buffer: 10485760
    - type: udp
      decoder: sflow
      listen: :6343
      workers: 6
      receive-buffer: 10485760

core:
  # Number of worker threads for processing flows.
  # Adjust based on the number of CPU cores available.
  default-sampling-rate: 20
  workers: 6

  # Classifiers for exporters (devices sending flows).
  exporter-classifiers:
    # Extract site from exporter name before the first '-'.
    # Example: "NYC-FW1" -> Site: "NYC".
    - ClassifySiteRegex(Exporter.Name, '^([^-]+)-', '$1')

    # Hardcode region, tenant, and role.
    - ClassifyRegion('Asia')
    - ClassifyTenant('Ubiquity')
    - ClassifyRole('Firewall')

  # Classifiers for interfaces based on name and description.
  interface-classifiers:
    # Match external interfaces such as Transit, PNI, PPNI, or IX.
    # Example: "Transit: Cogent" -> Connectivity: Transit, Provider: Cogent.
    - |
      ClassifyConnectivityRegex(Interface.Description, '^(?i)(transit|pni|ppni|ix):? ', '$1') &&
      ClassifyProviderRegex(Interface.Description, '^\\S+?\\s(\\S+)', '$1') &&
      ClassifyExternal()

    # Match point-to-point (P2P) links.
    # Example: "p2p link to 10.9" -> Connectivity: p2p, External.
    - |
      ClassifyConnectivityRegex(Interface.Description, '(?i)ge-', 'ge') &&
      ClassifyExternal()
    - |
      ClassifyConnectivityRegex(Interface.Description, '(?i)p2p', 'p2p') &&
      ClassifyExternal()

    # Match GRE interfaces by interface name (e.g., "gr-0/0/0.40").
    # Mark them as GRE connectivity and Internal.
    - |
      ClassifyConnectivityRegex(Interface.Name, '^(?i)gr-', 'GRE') &&
      ClassifyInternal()

    # Default classification for other internal interfaces.
    - ClassifyInternal()

```
