### DISCUSSION TITLE
TCP Flags in Akvorado Schema

### DISCUSSION THREAD

**Discussion by CliveMlt** [akvorado/akvorado#1800] [Q&A]
Hi,

I have a bare metal Akvorado v1.11.0 and I am trying to enable TCPFlags in the Schema. 
When I enable it, I can see it under ‘Dimensions’ and in the Clickhouse tables schema, however I stop receiving traffic flows.

Does it need to enabled under the 3 schemas in ‘config.yaml’ and is the configuration below correct?

```
      schema:
        disabled: []
        enabled: 
        - TCPFlags
        maintableonly: []
        notmaintableonly: []
        materialize: []
        customdictionaries: {}
```

**Comment by vincentbernat** [comment]
Did you restart the inlet as well? It should fetch an updated configuration from the orchestrator. If you don't centralize the configuration on the orchestrator, you should be sure to replicate the schema key inside the inlet configuration as well.

**Reply by CliveMlt** [reply]
Hi Vincent,

Thanks for the prompt reply, I have all the config in one config.yaml file as per config example below and I have tried to add the TCPFlags under the 3 Schemas and then stop/start Akvorado orchestrator, inlet and console. 
Can you let me know where we should add this config to enable the TCPFlags so I would be able to filter by the flags.

```
---
reporting:
    logging: {}
    metrics: {}
http:
    listen: :8080
    profiler: true
    cache:
        type: memory
clickhouse:
    servers:
        - 127.0.0.1:9000
    cluster: ""
    database: default
    username: default
    password: ""
    maxopenconns: 30
    dialtimeout: 5s
    tls:
        enable: false
        verify: true
        cafile: ""
        certfile: ""
        keyfile: ""
    skipmigrations: false
    kafka:
        topic: flows
        brokers:
            - 127.0.0.1:9092
        version: 2.8.1
        tls:
            enable: false
            verify: true
            cafile: ""
            certfile: ""
            keyfile: ""
            saslusername: ""
            saslpassword: ""
            saslmechanism: none
        consumers: 1
        groupname: clickhouse
        enginesettings: []
    resolutions:
        - interval: 0s
          ttl: 720h0m0s
        - interval: 1m0s
          ttl: 360h0m0s
        - interval: 5m0s
          ttl: 4320h0m0s
        - interval: 1h0m0s
          ttl: 8640h0m0s
    maxpartitions: 50
    systemlogttl: 720h0m0s
    prometheusendpoint: ""
    asns: {}
    networks: null
    networksources: {}
    networksourcestimeout: 10s
    orchestratorurl: ""
kafka:
    topic: flows
    brokers:
        - 127.0.0.1:9092
    version: 2.8.1
    tls:
        enable: false
        verify: true
        cafile: ""
        certfile: ""
        keyfile: ""
        saslusername: ""
        saslpassword: ""
        saslmechanism: none
    topicconfiguration:
        numpartitions: 1
        replicationfactor: 1
        configentries: {}
        configentriesstrictsync: true
geoip:
    asndatabase: [/opt/akvorado/GeoLite2-ASN.mmdb]
    geodatabase: [/opt/akvorado/GeoLite2-Country.mmdb]
    optional: true
schema:
    disabled: []
    enabled: []
    maintableonly: []
    not-main-table-only: []
    materialize: []
    customdictionaries: {}
inlet:
    - reporting:
        logging: {}
        metrics: {}
      http:
        listen: :8081
        profiler: true
        cache:
            type: memory
      flow:
        inputs:
            - decoder: netflow
              listen: 0.0.0.0:9181
              queuesize: 100000
              receivebuffer: 10485760
              timestampsource: netflow-packet
              type: udp
              usesrcaddrforexporteraddr: false
              workers: 4
        ratelimit: 0
      metadata:
        cacheduration: 30m0s
        cacherefresh: 1h0m0s
        cachecheckinterval: 2m0s
        cachepersistfile: ""
        providers:
            - agents: {}
              communities:
                ::/0:
                    - {our community}
              pollerretries: 1
              pollertimeout: 1s
              ports:
                ::/0: 161
              securityparameters: {}
              type: snmp
        workers: 1
        maxbatchrequests: 10
      routing:
        provider:
            collectasns: true
            collectaspaths: true
            collectcommunities: true
            keep: 5m0s
            listen: :10179
            rds: []
            ribpeerremovalbatchroutes: 5000
            ribpeerremovalmaxqueue: 10000
            ribpeerremovalmaxtime: 100ms
            ribpeerremovalsleepinterval: 500ms
            type: bmp
      kafka:
        topic: flows
        brokers:
            - 127.0.0.1:9092
        version: 2.8.1
        tls:
            enable: false
            verify: true
            cafile: ""
            certfile: ""
            keyfile: ""
            saslusername: ""
            saslpassword: ""
            saslmechanism: none
        flushinterval: 1s
        flushbytes: 104857599
        maxmessagebytes: 1000000
        compressioncodec: none
        queuesize: 32
      core:
        workers: 4
        exporter-classifiers: []
        interface-classifiers:
	{our classifiers}
        classifiercacheduration: 5m0s
        defaultsamplingrate: 2000
        overridesamplingrate: 2000
        asnproviders:
            - flow
            - routing
        netproviders:
            - flow
            - routing
      schema:
        disabled: []
        enabled: []
        maintableonly: []
        not-main-table-only: []
        materialize: []
        customdictionaries: {}
console:
    - reporting:
        logging: {}
        metrics: {}
      http:
        listen: :8082
        profiler: true
        cache:
            type: memory
      defaultvisualizeoptions:
        graphtype: stacked
        start: 24 hours ago
        end: now
        filter: InIfBoundary = external
        dimensions:
            - SrcAS
            - DstAS
        limit: 10
      homepagetopwidgets:
        - src-as
        - dst-as
        - src-port
        - protocol
        - src-country
        - etype
      homepagegraphfilter:
      homepagegraphtimerange: 24h0m0s
      dimensionslimit: 50
      cachettl: 3h0m0s
      clickhouse:
        servers:
            - 127.0.0.1:9000
        cluster: ""
        database: default
        username: default
        password: ""
        maxopenconns: 10
        dialtimeout: 5s
        tls:
            enable: false
            verify: true
            cafile: ""
            certfile: ""
            keyfile: ""
      auth:
        headers:
            login: Remote-User
            name: Remote-Name
            email: Remote-Email
            logouturl: X-Logout-URL
        defaultuser:
            login:
            name: Network User
            email: ""
            logouturl: ""
      database:
        driver: sqlite
        dsn: /opt/akvorado/console.sqlite
        savedfilters: []
      schema:
        disabled: []
        enabled: []
        maintableonly: []
        not-main-table-only: []
        materialize: []
        customdictionaries: {}
demoexporter: []


```
