### DISCUSSION TITLE
How to connect clickhouse?

### DISCUSSION THREAD

**Discussion by onik282** [akvorado/akvorado#1814] [Q&A]
Hello!
I want to connect akvarado to an external clickhouse cluster.
in akvarado.yml:
```
clickhouse:
  orchestrator-url: http://akvorado-orchestrator:8080
  kafka:
    consumers: 4
  servers:
    - 192.168.4.4:9000
  username: akvorado
  password: akvorado_pass
  database: akvorado
  cluster: akvorado-click
```

and i copy init.sh script and run it on clickhouse server.
but akvorado doesn't initialize the database, and it doesn't even seem to connect.
pleas, help
