### DISCUSSION TITLE
console sqlite database

### DISCUSSION THREAD

**Discussion by Rico29** [akvorado/akvorado#185] [Q&A]
Hello,
I'm unable to setup a sqlite database to store user related settings

in akvorado.yml
```
console:
  homepage-top-widgets: [src-as, src-country, etype]
  default-visualize-options:
    start: 1 day ago
    end: now
  database:
    driver: sqlite
    dsn: /var/lib/akvorado/console.sqlite
```

when docker-compose up :
```
akvorado-console exited with code 1
akvorado-console            | {"level":"error","time":"2022-10-04T14:29:33Z","caller":"akvorado/console/database/logs.go:34","module":"akvorado/console/database","message":"failed to initialize database, got error
 unable to open database file: no such file or directory"}
akvorado-console            | Error: unable to initialize database component: unable to open database: unable to open database file: no such file or directory

```
folder exists, file exists and is chmod 777

what am I missing ?
regards
Cédric
