### DISCUSSION TITLE
exporter is not a snmp pollable ip -> snmp agent map format?

### DISCUSSION THREAD

**Discussion by wouterprins** [akvorado/akvorado#226] [Q&A] [answered]
Hi, as per the documentation: "If your exporter cannot answer SNMP requests on the source IP address, you can specify an alternative address with inlet.snmp.agents."

What would be the format of this "map"?
Current configuration:

```
inlet:
  snmp:
    workers: 10
    agents: 192.168.255.248
    communities: public
```
Results in:

akvorado-orchestrator_1     | * 'Inlet[0].SNMP.Agents' expected a map, got 'string'

Does it expect a 'go' map configuration syntax? or a mapping from the exporter source-ip towards an snmp-agent?

**Comment by vincentbernat** [comment, marked as answer]
A map is an associative array. For each exporter, you need to map its IP address with the IP address it will accept SNMP requests:

```yaml
inlet:
 snmp:
  agents:
   192.168.255.248: 192.168.255.1
   192.168.255.249: 192.168.255.2
```
