### DISCUSSION TITLE
Juniper SNMP in routing instance

### DISCUSSION THREAD

**Discussion by arphillips06** [akvorado/akvorado#236] [Q&A]
Hi, 

I'm currently testing akvorado in our lab which is in a Junos routing instance, I see that I am getting "SNMP cache miss" errors increasing meaning no data on the frontend. 

As far as I can work out the inlet snmp config in akvorado.yaml has a section for communities. So mine looks like this, 

```
inlet:
  snmp:
    agents:
      172.30.0.1: 172.30.0.1
    workers: 10
    communities:
      ::/0: RI-NAME@akvorado
```

That community structure is how Junos does snmp in routing instances and works on a snmpwalk.  If I tcpdump it I see this. 

```
14:50:56.137207 IP _gateway.snmp > pmacct01.51983:  C="VPN-61007@akvorado" GetResponse(153)  system.sysName.0="RI-NAME@xxxx.lab" interfaces.ifTable.ifEntry.ifDescr.574=[noSuchInstance] 31.1.1.1.18.574=[noSuchInstance] 31.1.1.1.15.574=[noSuchInstance] interfaces.ifTable.ifEntry.ifDescr.550=[noSuchInstance] 31.1.1.1.18.550=[noSuchInstance] `31.1.1.1.15.550=[noSuchInstance]
```

Is there something I'm missing or is this just a hopeless task and I should deploy in the global table? 

Thanks
