### DISCUSSION TITLE
Not working BMP

### DISCUSSION THREAD

**Discussion by mellfice** [akvorado/akvorado#296] [Q&A] [answered]
Hello
 
I have installed akvorado, and configured the BMP protocol on my router. But in the check commands I see the connecting state. I tried to manually set some parameters for BMP in akvorado.yaml file. But it didn't work. The akvorado version is 1.6.3. 

```
docker-compose exec akvorado-orchestrator akvorado version
akvorado v1.6.3
  Build date: 2022-11-26T11:43:14+0000
  Built with: go1.19.3
```

The router is a Juniper MX. Its configuration:

```
show configuration routing-options bmp
connection-mode active;
monitor enable;
route-monitoring {
    post-policy;
}
station-address x.x.x.x;
station-port 10179;
station akvorado;
```
 
Logs with akvorado:

```
docker-compose logs --tail=100 -f akvorado-inlet | grep bmp
akvorado-inlet_1            | {"level":"info","time":"2022-11-29T14:31:02Z","caller":"akvorado/inlet/bmp/root.go:76","module":"akvorado/inlet/bmp","message":"starting BMP component"}
akvorado-inlet_1            | {"level":"info","time":"2022-11-29T14:31:02Z","caller":"akvorado/inlet/bmp/root.go:115","module":"akvorado/inlet/bmp","message":"stopping BMP component"}
akvorado-inlet_1            | {"level":"info","time":"2022-11-29T14:31:02Z","caller":"akvorado/inlet/bmp/root.go:113","module":"akvorado/inlet/bmp","message":"BMP component stopped"}
akvorado-inlet_1            | {"level":"info","time":"2022-11-29T14:31:06Z","caller":"akvorado/inlet/bmp/root.go:76","module":"akvorado/inlet/bmp","message":"starting BMP component"}
akvorado-inlet_1            | {"level":"info","time":"2022-11-29T14:31:11Z","caller":"akvorado/inlet/bmp/root.go:115","module":"akvorado/inlet/bmp","message":"stopping BMP component"}
akvorado-inlet_1            | {"level":"info","time":"2022-11-29T14:31:11Z","caller":"akvorado/inlet/bmp/root.go:113","module":"akvorado/inlet/bmp","message":"BMP component stopped"}
akvorado-inlet_1            | {"level":"info","time":"2022-11-29T14:31:13Z","caller":"akvorado/inlet/bmp/root.go:76","module":"akvorado/inlet/bmp","message":"starting BMP component"}
akvorado-inlet_1            | {"level":"info","time":"2022-11-29T14:31:14Z","caller":"akvorado/inlet/bmp/root.go:115","module":"akvorado/inlet/bmp","message":"stopping BMP component"}
akvorado-inlet_1            | {"level":"info","time":"2022-11-29T14:31:14Z","caller":"akvorado/inlet/bmp/root.go:113","module":"akvorado/inlet/bmp","message":"BMP component stopped"}
akvorado-inlet_1            | {"level":"info","time":"2022-11-29T14:31:19Z","caller":"akvorado/inlet/bmp/root.go:76","module":"akvorado/inlet/bmp","message":"starting BMP component"}
^CERROR: Aborting.
```
`curl -s http://x.x.x.x:8081/api/v0/inlet/metrics | grep bmp `- blank output 
 
Akvorado settings:

```
docker-compose exec akvorado-orchestrator akvorado orchestrator --check --dump /etc/akvorado.yaml

  bmp:
    listen: 0.0.0.0:10179
    rds:
    - "0:0"
    collectasns: true
    collectaspaths: true
    collectcommunities: true
    keep: 30m0s
    peerremovalmaxtime: 200ms
    peerremovalsleepinterval: 500ms
    peerremovalmaxqueue: 10000
    peerremovalminroutes: 5000
```

Thank you for your help

**Comment by vincentbernat** [comment]
Is your `docker-compose.yml` up-to-date?

**Comment by mellfice** [comment, marked as answer]
Current my `docker-compose.yml` file: 

```
cat docker-compose.yml
---
version: "3"

volumes:
  akvorado-zookeeper:
  akvorado-kafka:
  akvorado-geoip:
  akvorado-clickhouse:
  akvorado-run:
  akvorado-console-db:

services:
  geoip:
    # Put GEOIP_ACCOUNT_ID and GEOIP_LICENSE_KEY values in `.env` file.
    image: maxmindinc/geoipupdate:v4
    environment:
      - GEOIPUPDATE_ACCOUNT_ID
      - GEOIPUPDATE_LICENSE_KEY
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-ASN GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=48
    volumes:
      - akvorado-geoip:/usr/share/GeoIP

  zookeeper:
    image: bitnami/zookeeper:3.6
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped
    volumes:
      - akvorado-zookeeper:/bitnami/zookeeper
  kafka:
    image: bitnami/kafka:2.8.1
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_DELETE_TOPIC_ENABLE=true
    restart: unless-stopped
    depends_on:
      - zookeeper
    volumes:
      - akvorado-kafka:/bitnami/kafka
    healthcheck:
      interval: 20s
      timeout: 10s
      retries: 3
      test: ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.4.0
    restart: unless-stopped
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - SERVER_SERVLET_CONTEXT_PATH=/kafka-ui
    labels:
      - traefik.enable=true
      - traefik.http.routers.kafka-ui.entrypoints=private
      - traefik.http.routers.kafka-ui.rule=PathPrefix(`/kafka-ui`)

  # If you need to build from the source, uncomment the build option
  # here and use `docker-compose build akvorado-service`.
  akvorado-service: &akvorado-image
    # build: {context: .}
    image: ghcr.io/akvorado/akvorado:latest
    command: version

  akvorado-orchestrator:
    <<: *akvorado-image
    restart: unless-stopped
    command: orchestrator /etc/akvorado.yaml
    volumes:
      - ./akvorado.yaml:/etc/akvorado.yaml:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.akvorado-orchestrator.entrypoints=private # it exposes configuration files with passwords
      - traefik.http.routers.akvorado-orchestrator.rule=PathPrefix(`/api/v0/orchestrator`)
      - traefik.http.services.akvorado-orchestrator.loadbalancer.server.port=8080
  akvorado-console:
    <<: *akvorado-image
    restart: unless-stopped
    command: console http://akvorado-orchestrator:8080
    volumes:
      - akvorado-console-db:/run/akvorado
    labels:
      - traefik.enable=true
      - traefik.http.routers.akvorado-console.rule=PathPrefix(`/`)
      - traefik.http.services.akvorado-console.loadbalancer.server.port=8080
      - traefik.http.middlewares.testheader.headers.customrequestheaders.Remote-User=alfred
      - traefik.http.middlewares.testheader.headers.customrequestheaders.Remote-Name=Alfred Pennyworth
      - traefik.http.middlewares.testheader.headers.customrequestheaders.Remote-Email=alfred@example.com
  akvorado-inlet:
    <<: *akvorado-image
    ports:
      - 9080:9080/udp
      - 10179:10179/tcp
    restart: unless-stopped
    command: inlet http://akvorado-orchestrator:8080
    volumes:
      - akvorado-geoip:/usr/share/GeoIP:ro
      # If you prefer to use geo IP databases from host, comment the
      # above line and uncomment this one:
      # - /usr/share/GeoIP:/usr/share/GeoIP:ro
      - akvorado-run:/run/akvorado
    labels:
      - traefik.enable=true
      - traefik.http.routers.akvorado-inlet.rule=PathPrefix(`/api/v0/inlet`)
      - traefik.http.services.akvorado-inlet.loadbalancer.server.port=8080
      - akvorado.conntrack.fix=true
  akvorado-conntrack-fixer:
    <<: *akvorado-image
    cap_add:
      - NET_ADMIN
    command: conntrack-fixer
    restart: unless-stopped
    network_mode: host
    healthcheck:
      disable: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  clickhouse:
    image: clickhouse/clickhouse-server:22.8
    volumes:
      - ./orchestrator/clickhouse/data/docker-entrypoint.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
      - akvorado-clickhouse:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_INIT_TIMEOUT=60
    restart: unless-stopped
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      test: ["CMD", "wget", "-T", "1", "--spider", "--no-proxy", "http://clickhouse:8123"]
    labels:
      - traefik.enable=true
      - traefik.http.routers.clickhouse.entrypoints=private
      - traefik.http.routers.clickhouse.rule=PathPrefix(`/clickhouse`)
      - traefik.http.services.clickhouse.loadbalancer.server.port=8123

  traefik:
    image: traefik:2.6
    restart: unless-stopped
    command:
      - --api=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # - --providers.docker.allowEmptyServices=true
      - --entrypoints.private.address=:8080
      - --entrypoints.public.address=:8081
    ports:
      - 127.0.0.1:8080:8080/tcp
      - 8081:8081/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

```

**Reply by vincentbernat** [reply]
Check with `tcpdump` if you see incoming TCP connections for port 10179.

**Reply by mellfice** [reply]
> Check with `tcpdump` if you see incoming TCP connections for port 10179.

Yes, I see incoming connections with `tcpdump`. 

I am also attaching part of the `akvorado.yaml file`

Metrics also blank
 
```
sudo tcpdump -vvv port 10179 

akvorado.10179 > x.x.x.x.60946: Flags [S.], cksum 0x9a64 (incorrect -> 0x4a24), seq 4118835951, ack 1235452801, win 65160, options [mss 1460,sackOK,TS val4181653596 ecr 988212511,nop,wscale 7], length 0

    x.x.x.x.60946 > akvorado.10179: Flags [S], cksum 0x8fb4 (correct), seq 1235452800, win 65535, options [mss 9130,nop,wscale 1,nop,nop,TS val 988270911 ecr 0,sackOK,eol], length 0

    akvorado.10179 > x.x.x.x.60946: Flags [S.], cksum 0x9a64 (incorrect -> 0x2a3a), seq 4118835951, ack 1235452801, win 65160, options [mss 1460,sackOK,TS val4181661766 ecr 988212511,nop,wscale 7], length 0

    x.x.x.x.51104 > akvorado.10179: Flags [S], cksum 0x2abb (correct), seq 3309625610, win 65535, options [mss 9130,nop,wscale 1,nop,nop,TS val 988316542 ecr 0,sackOK,eol], length 0

    akvorado.10179 > x.x.x.x.51104: Flags [S.], cksum 0x9a64 (incorrect -> 0x9bae), seq 1564909145, ack 3309625611, win 65160, options [mss 1460,sackOK,TS val4181707399 ecr 988316542,nop,wscale 7], length 0
```


```
sudo docker-compose ps
               Name                              Command                  State                                                    Ports
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
akvorado_akvorado-conntrack-fixer_1   /usr/local/bin/akvorado co ...   Up
akvorado_akvorado-console_1           /usr/local/bin/akvorado co ...   Up (healthy)   8080/tcp
akvorado_akvorado-inlet_1             /usr/local/bin/akvorado in ...   Up (healthy)   0.0.0.0:10179->10179/tcp,:::10179->10179/tcp, 8080/tcp, 0.0.0.0:9080->9080/udp,:::9080->9080/udp
akvorado_akvorado-orchestrator_1      /usr/local/bin/akvorado or ...   Up (healthy)   8080/tcp
akvorado_akvorado-service_1           /usr/local/bin/akvorado ve ...   Exit 0
akvorado_clickhouse_1                 /entrypoint.sh                   Up (healthy)   8123/tcp, 9000/tcp, 9009/tcp
akvorado_geoip_1                      /usr/bin/entry.sh                Exit 1
akvorado_kafka-ui_1                   /bin/sh -c java $JAVA_OPTS ...   Up             8080/tcp
akvorado_kafka_1                      /opt/bitnami/scripts/kafka ...   Up (healthy)   9092/tcp
akvorado_traefik_1                    /entrypoint.sh --api=true  ...   Up             80/tcp, 127.0.0.1:8080->8080/tcp, 0.0.0.0:8081->8081/tcp,:::8081->8081/tcp
akvorado_zookeeper_1                  /opt/bitnami/scripts/zooke ...   Up             2181/tcp, 2888/tcp, 3888/tcp, 8080/tcp

```
```
sudo docker-compose exec akvorado-orchestrator akvorado orchestrator --check --dump /etc/akvorado.yaml

inlet:
- reporting:
    logging: {}
    metrics: {}
  http:
    listen: 0.0.0.0:8080
    profiler: false
  flow:
    inputs:
    - decoder: netflow
      listen: 0.0.0.0:9080
      queuesize: 100000
      receivebuffer: 10485760
      type: udp
      workers: 6
    ratelimit: 0
  snmp:
    cacheduration: 30m0s
    cacherefresh: 1h0m0s
    cachecheckinterval: 2m0s
    cachepersistfile: ""
    pollerretries: 1
    pollertimeout: 1s
    pollercoalesce: 10
    workers: 10
    communities:
      ::/0: ytpfdbcbvjcnm
    securityparameters: {}
    agents: {}
    ports:
      ::/0: 161
  bmp:
    listen: 0.0.0.0:10179
    rds:
    - "0:0"
    collectasns: true
    collectaspaths: true
    collectcommunities: true
    keep: 30m0s
    peerremovalmaxtime: 200ms
    peerremovalsleepinterval: 500ms
    peerremovalmaxqueue: 10000
    peerremovalminroutes: 5000

```
