### DISCUSSION TITLE
Documentation: SNMP v2 community

### DISCUSSION THREAD

**Discussion by sm3ulc** [akvorado/akvorado#301] [Q&A]
Unable to find what default v2-community that's used and also if/how to use different per exporter. Also confusing nomenclature when
the normal default community is **public** and this text maps to something for community per network? Is the default community **public**?

**"communities" is a map from a subnets to the SNMPv2 community to use for exporters in the provided subnet. Use **::/0** to set the default value.**

Please provide more clear default settings in the default docker-compose.yml. 

https://demo.akvorado.net/docs/configuration#snmp

**Comment by NoifP** [comment]
snmp is configured in akvorado.yaml in the inlet section.
```yaml
inlet:
  snmp:
    communities:
      ::/0: public
```

or alternatively set the same community for everything
```yaml
inlet:
  snmp:
    communities: "public"
```
