### DISCUSSION TITLE
GeoIP city/country data not being added to flows

### DISCUSSION THREAD

**Discussion by MattKobayashi** [akvorado/akvorado#302] [Q&A] [answered]
Hi all,

I've recently deployed a new Akvorado instance and have tied in the Maxmind GeoIP updater to provide the MMDB files. It seems that the GeoIP city/country data is not being added to flows when they're exported, I'm seeing 100% "Others" for the country breakdown in the console. I've tried configuring the GeoLite2-City.mmdb and GeoLite2-Country.mmdb files in Akvorado without success. I'm not sure how to debug the GeoIP component of the inlet service to see what's wrong, is someone able to help point me in the right direction?

Configuration file `geoip` section:
```
  geoip:
    asn-database: "/home/akvorado/geoip/GeoLite2-ASN.mmdb"
    geo-database: "/home/akvorado/geoip/GeoLite2-City.mmdb"
    optional: false
```

Output of `ls -hal /home/akvorado/geoip`:
```
total 80M
drwxrwxr-x 2 akvorado akvorado 4.0K Dec  1 16:00 .
drwxr-x--- 5 akvorado akvorado 4.0K Dec  1 00:16 ..
-rw------- 1 root     root        0 Nov 29 05:14 .geoipupdate.lock
-rw-r--r-- 1 root     root     7.7M Nov 29 05:16 GeoLite2-ASN.mmdb
-rw-r--r-- 1 root     root      67M Nov 29 05:16 GeoLite2-City.mmdb
-rw-r--r-- 1 root     root     5.4M Nov 29 05:14 GeoLite2-Country.mmdb
```
