### DISCUSSION TITLE
DimensionsLimit - Increase to Infinity?

### DISCUSSION THREAD

**Discussion by cmurrayis** [akvorado/akvorado#448] [Q&A]
Hi Team,

I'm wanting to do some deep investigations to our network traffic origins and finding the DimensionsLimit  <50 is not helping. I'm using the docker image and cannot see how I can remove this limit.

In the Source I can manually change the limit however would be required to recompile with golang etc.

TIA

**Comment by vincentbernat** [comment]
It's configurable here: https://demo.akvorado.net/docs/configuration#console-service

**Comment by cmurrayis** [comment]
Hi Vincent, I did try this however I suspect my formatting or code is incorrect:

```
console:
  homepage-top-widgets: [src-as, src-country, etype]

  default-visualize-options:
    start: 1 day ago
    end: now
    filter: InIfBoundary = external
    dimensions-limit: ≤ 50 (I have also tried just 50 or 100
    dimensions:
      - ExporterName
```

```
akvorado-akvorado-orchestrator-1     | Error: invalid configuration:
akvorado-akvorado-orchestrator-1     | invalid key "Console[0].DefaultVisualizeOptions.dimensions-limit"
```
