### DISCUSSION TITLE
snmp v3 config

### DISCUSSION THREAD

**Discussion by absmith** [akvorado/akvorado#494] [Q&A] [answered]
Could someone show me an example of the security-parameters to enable snmpv3? I can't seem to figure out the correct syntax in the  akvorado.yaml for this section.

**Comment by vincentbernat** [comment, marked as answer]
```
inlet:
 snmp:
  security-parameters:
    username: alfred
    authentication-protocol: sha
    authentication-passphrase: something
    privacy-protocol: aes
    privacy-passphrase: somethingelse
```
