### DISCUSSION TITLE
IPv6-only network configuration

### DISCUSSION THREAD

**Discussion by mathieu-gilloots** [akvorado/akvorado#673] [Q&A]
Hello,  
I'm trying to set up akvorado on an IPV6-only network.  

My VMs use NAT64 to get ipv4 webiste connectivity (like github.com...) no problem for that.  

When I see logs on inlet container I get :   
```
"level":"error","error":"request timeout (after 1 retries)","exporter":"172.18.0.1","time":"2023-05-03T23:35:07Z","caller":"akvorado/inlet/snmp/poller.go:186","module":"akvorado/inlet/snmp","message":"unable to GET (4 OIDs)"}
```
In fact, 172.18.0.1 is my docker internal network, because netflow trace has been received on the host ipv6.  

I try to disable userland-proxy, but without that, I can't get access to countainer from the outside. (no IPV6 binded only 0.0.0.0:2250 for example. without any docker daemon config changes, I bind also ipv6 : `0.0.0.0:2055->2055/udp, :::2055->2055/udp`

My inlet.yaml :  
```
snmp:
  workers: 10
  communities:
    ::/0: public
  security-parameters:
    user-name: mysuperuser
    authentication-protocol: SHA
    authentication-passphrase: mysuperpassword
    privacy-protocol: AES
    privacy-passphrase: mysuperpassword
flow:
  inputs:
    - type: udp
      decoder: netflow
      listen: 0.0.0.0:2055
      workers: 6
      receive-buffer: 10485760

```

Also, any advice to configure 1 user / password per snmp connections / router ?

Thanks

**Comment by rnavarro** [comment]
I ran into a similar issue with my IPv6 only setup.

To get things working I had to fix the exporter IP address to be the IPv6 address and _not_ the IPv4 address.

I have a brocade switch, so I ended up doing something like:

`sflow agent-ip fd5f:56da:bbab:a::1`

**Comment by rnavarro** [comment]
> Also, any advice to configure 1 user / password per snmp connections / router ?

something like this should work:

```
snmp:
  workers: 10
  communities:
    fd5f:56da:bbab:a::1: public
    fd5f:56da:bbab:b::1: private
```

**Comment by mathieu-gilloots** [comment]
Hello @rnavarro,
thanks your reply, but I don't think it will do the trick.
In deed my netflow agent already sent trafic on akvorado IPV6, and has a source-ip in ipv6.
The problem is : docker translate the ipv6 receive on the akvorado host to private docker network ipv4 (172.16.x.x), for that reason akvorado coun't sent the SNMP on the real ipv6 address.

Thanks.

**Reply by rnavarro** [reply]
Ah it looks like I enabled IPv6 connectivity for docker, sorry forgot about that step.

To do so, I created a file on my system: /etc/docker/daemon.json:

```
{
  "ipv6": true,
  "fixed-cidr-v6": "2001:db8:1::/64"
}
```

Feel free to change the range as needed, that's just the range that docker has in their documentation. That config will enable IPv6 for all docker containers, outside of docker compose.

I then modified my akvorado docker-compose.yml files to include:

```
networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8:2::/64
          gateway: 2001:db8:2::1
```

This assigns IPv6 addresses to the akvorado containers, change the subnet as needed.

Restart the docker daemon and re-create the akvorado containers.

The containers should come up with an IPv6 address that can be used for outbound communication.

**Reply by rnavarro** [reply]
I also changed the flow input listen address to listen to all protocols, not just IPv4:

```
flow:
  inputs:
    - type: udp
      decoder: netflow
      listen: :2055
      workers: 6
      receive-buffer: 10485760
    - type: udp
      decoder: sflow
      listen: :6343
      workers: 6
      receive-buffer: 10485760
```

Note `:2055` vs `0.0.0.0:2055`
