### DISCUSSION TITLE
Question: Adding Let's Encrypt certificates to the Akvorado dashboard

### DISCUSSION THREAD

**Discussion by blackphantom39** [akvorado/akvorado#699] [Q&A] [answered]
Hi,

we want to evaluate the use of akvorado, but require the dashboard to use SSL certificates. As you use a treafik proxy we tried to use its built-in functionality for managing certificates with let's encrypt. Unfortunately, this didn't work out, as it is still somewhat unclear to me how the dashboard actually gets addressed by traefik.
Therefore, I want to ask, if someone knows how to achieve this using the docker-compose approach. Thanks in advance.

**Comment by vincentbernat** [comment, marked as answer]
You need to make traefik listen on 80 instead of 8081.

I think something like that is likely to work. You need to add the publicsecure endpoint to the `akvorado-console`.

```yaml
  traefik:
    image: traefik:2.6
    restart: unless-stopped
    command:
      - --api=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # - --providers.docker.allowEmptyServices=true
      - --entrypoints.private.address=:8080
      - --entrypoints.public.address=:8081
      - --entrypoints.publicsecure.address=:8443
      - --certificatesresolvers.letsencrypt.acme.email=youremail@example.com
      - --certificatesresolvers.letsencrypt.amce.storage=/etc/traefik/acme/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=public
    ports:
      - 127.0.0.1:8080:8080/tcp
      - 80:8081/tcp
      - 443:8443/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - akvorado-acme:/etc/traefik/acme
```
