### DISCUSSION TITLE
SrcAS only shows the BGP neighbour

### DISCUSSION THREAD

**Discussion by mellfice** [akvorado/akvorado#750] [Q&A]
Hello.
Have you noticed that when using the filter `SrcAS = xxxx`, the data will only be displayed if there is a BGP connection (peer or IX) with this AS. If you specify an AS that has no BGP connection, it will not show any data. `SrcNetPrefix/Addr` from this AS will work correctly. Is it possible to specify filter `SrcAS = xxxx` and receive data from traffic which does not have BGP connectivity?
Thank you!

**Comment by Serverlag** [comment]
I feel like I may have hit this issue too, or at least something similar. I have two transit providers in Australia, I take a default route from both of them only, no full table. I connect to a few local internet exchange points in Australia also, and pick up the various prefixes from peers on said IXP. If I have a bilateral BGP session with them over the IXP, I can search for their traffic using "SrcAS" as a filter. If I learn their routes via the route servers, I cannot. Same goes for any Source prefixes learned via transit, the SrcAS for all this traffic is actually my transit provider, rather than the origin BGP ASN. 

It feels like the SrcAS is not actually the Origin AS of the traffic, but the SrcAS of the BGP session it was learned over. I do not provide Akvorado a BMP feed, I currently just use GeoIP and inline jflow, and my expectation of what is explained in the documentation is that should do a lookup against the source IP address against the GeoIP database and set the SrcAS to the ASN from the GeoIP lookup. 

I would love some clarification with this.

**Reply by vincentbernat** [reply]
The default is to use the AS from the flow, then from the routing provider (you did not configure it), and then from geoip. So, I assume your flows come with an AS number. You can change the defaults to only use geoip with:

```yaml
inlet:
 core:
  asn-providers:
    - geoip
```

**Comment by Serverlag** [comment]
Thanks for that, will give it a go! Really appreciate the quick response.

**Comment by noll26** [comment]
Not work for my

After include this lines, akvorado return 404 not found error.

```
core:
  asn-providers:
    - geoip
  workers: 6
  exporter-classifiers:
    # This is an example. This should be customized depending on how
    # your exporters are named.
    - ClassifySiteRegex(Exporter.Name, "^([^-]+)-", "$1")
    - ClassifyRegion("BR")

```
