### DISCUSSION TITLE
Documentation for defaultvisualizeoptions and homepagetopwidgets appears to be incorrect (v1.8.3)

### DISCUSSION THREAD

**Discussion by packetThrower** [akvorado/akvorado#754] [Q&A]
The documentation states to use this in console.yaml config:

```
console:
  homepage-top-widgets: [src-as, src-country, etype]
  default-visualize-options:
    start: 1 day ago
    end: now
    filter: InIfBoundary = external
    dimensions:
      - ExporterName
```
I was getting errors:

```
Error: invalid configuration:
invalid key "Console[0].console"
Error: invalid configuration:
invalid key "Console[0].console"
Error: invalid configuration:
invalid key "Console[0].console"
Error: invalid configuration:
```

But, after much trial and error, I ran `sudo docker-compose run akvorado-orchestrator orchestrator /dev/null --dump --check` and discovered the syntax to be wrong.

The correct syntax in console.yaml is:

```
defaultvisualizeoptions:
  graphtype: stacked
  start: 6 hours ago
  end: now
  filter: InIfBoundary = external
  dimensions:
      - SrcAS
  limit: 10
homepagetopwidgets:
  - src-as
  - src-port
  - protocol
  - src-country
  - etype
 ```
Once I made the changes, all the settings started to work.
