### DISCUSSION TITLE
New metadata + static configuration

### DISCUSSION THREAD

**Discussion by atiide** [akvorado/akvorado#775] [Q&A]
In my setup I am not really interested in enriching flows with SNMP interface data. I am really only interested in geoIP+asn info. I was hoping this metadata+static configuration would bypass SNMP. But when I configured everything I still get

curl -s http://127.0.0.1:8081/api/v0/inlet/metrics | grep '^akvorado_inlet' | grep _error

`akvorado_inlet_core_flows_errors{error="SNMP cache miss",exporter="x.x.x.x"} 3.286831e+06`

curl -s http://127.0.0.1:8080/api/v0/orchestrator/configuration/inlet
```   
provider:
    exporters:
        x.x.x.x/32:
            name: exporter1
            default:
                name: unknown
                description: Unknown interface
                speed: 100000
    type: static
```
Have I misunderstood the purpose of static configuration part? Theoretically if SNMP would reply once but none of the interface indexes match default value from static configuration would be used instead for all the unmatched if indexes.
