### DISCUSSION TITLE
SNMP v2 and v3

### DISCUSSION THREAD

**Discussion by arphillips06** [akvorado/akvorado#806] [Q&A] [answered]
Could someone let me know if this is correct? Most of our estate uses SNMPv2 but we are onboarding some other devices that use v3. If I understand the docs correctly then if v3 'security-parameters' isn't matched then it will use v2. 

At the moment I have

```
snmp:
  workers: 10
  communities:
    publiccomm
```
This is working fine. To add the v3 I think I need to have this.

```
snmp:
  workers: 10
  communities:
    publiccomm
  security-parameters:
    username: COMPANY-SNMP
    authentication-protocol: md5
    authentication-passphrase: passphrase
    privacy-protocol: aes
    privacy-passphrase: passphrase2
```

What I expect to happen is that traffic will be parsed through SNMPv3, if no match fall back to v2.

**Comment by vincentbernat** [comment, marked as answer]
You need more something like this:

```yaml
snmp:
 communities:
  publiccomm
 security-parameters:
  172.16.1.0/24:
    username: COMPANY-SNMP
```
