### DISCUSSION TITLE
SNMP agents v4 exporter, v6 SNMP address

### DISCUSSION THREAD

**Discussion by arphillips06** [akvorado/akvorado#812] [Q&A]
I have some routers that are sending netflow on v4 addresses and have been configured for v6 SNMP. These aren't in my control so was hoping that I could make this work in Akvorado rather then having to get changes made on the routers.

The relevant part of my SNMP config is this.
```
snmp:
  agents:
    10.10.10.10: cafe:beef:2::e
```
Is this viable? Or just it need to be mapped to a v4 address?

Thanks

**Comment by vincentbernat** [comment]
I think it should work. Doesn't it?

**Reply by arphillips06** [reply]
Sorry for taking so long to get back to you. The owners of the ranges have just responded saying that they aren't getting anymore rejected v4 SNMP but equally aren't seeing any v6 SNMP of any kind on the firewall filters.

**Reply by vincentbernat** [reply]
Check with `tcpdump` on the server running Akvorado to check if you see outgoing SNMP requests.

**Reply by arphillips06** [reply]
I can't see anything leaving for SNMP if the agent is set for the v4 to v6. If I comment out the agent then it works as expected and I can see SNMP egress towards the address that the netflow was received on.  

I've included my entire SNMP config just in case. 

```
snmp:
  workers: 10
  communities:
    COMM
  security-parameters:
    10.10.10.0/24:
      username: SNMPUSER
      authentication-protocol: md5
      authentication-passphrase: PASSPHRASE
      privacy-protocol: aes
      privacy-passphrase: PASSPHRASE
    cafe:beef:2::/48:
      username: SNMPUSER
      authentication-protocol: md5
      authentication-passphrase: PASSPHRASE
      privacy-protocol: aes
      privacy-passphrase: PASSPHRASE
  agents:
    10.10.10.10: cafe:beef:2::e
    ```
