### DISCUSSION TITLE
Deploying Akvorado on Kubernetes

### DISCUSSION THREAD

**Discussion by madtema** [akvorado/akvorado#817] [Q&A] [answered]
Hello. I'm trying to deploy Akvorado on Kubernetes. When starting a container with an orchestrator, an error appears that the orchestrator config is incorrect

```
Error: invalid configuration:
invalid key "PORT"
invalid key "PORT"
invalid key "PORT"
invalid key "PORT"
invalid key "PORT"
invalid key "SERVICE"
invalid key "SERVICE"
```
At the same time, everything starts correctly in the docker and works fine with the same config. At first I assumed that the problem was in the config, initially I connected it to the container through the configMap and volumeMounts, but the problem was repeated even when I rebuilt the container with the config files inside and even when I launched the akvorado orchestrator with the /dev/null parameter.

Here is the orchestrator manifest I am using

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  akvorado-orchestrator
  namespace: my-akvorado
  labels:
    app:  akvorado-orchestrator
    
spec:
  selector:
    matchLabels:
      app: akvorado-orchestrator
  template:
    metadata:
      labels:
        app: akvorado-orchestrator
    spec:
      containers:
        - name: akvorado-orchestrator
          image: ghcr.io/akvorado/akvorado:1.8.3
          #args: ["orchestrator", "/etc/akvorado/akvorado.yaml"]
          args: ["orchestrator", "--dump", "--check", "/dev/null"]
          # volumeMounts:
              # - name: akvorado-config
                # mountPath: /etc/akvorado/
      # volumes:
        # - name: akvorado-config
          # configMap:
            # name: akvorado-config
            # defaultMode: 0777
```
any clue will be welcome, thx

**Comment by vincentbernat** [comment, marked as answer]
I think that Kube may set some environment variables that Akvorado interprets as its configuration. Rename your container from `akvorado-orchestrator` to `akvorado-X-orchestrator` to check.

**Reply by madtema** [reply]
Thank you for help. The problem was in the naming of Service object and gone when i changed its name from akvorado-orchestrator.

```
apiVersion: v1
kind: Service
metadata:
  name: akvorado-orchestrator
  namespace: my-akvorado
spec:
  selector:
    app: akvorado-orchestrator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
```
