### DISCUSSION TITLE
SNMPv3 issue

### DISCUSSION THREAD

**Discussion by enkikun** [akvorado/akvorado#863] [Q&A]
Hi!
Documentation says that snmpv3 **privacy-protocol** option can be omitted, but inlet service doesn't start in that case with error:
```
akvorado-akvorado-inlet-1  | * error decoding 'Metadata.Provider.Config.SecurityParameters': unable to decode "SecurityParameters": 1 error(s) decoding:
akvorado-akvorado-inlet-1  |
akvorado-akvorado-inlet-1  |
akvorado-akvorado-inlet-1  | * error decoding '[::/0].PrivacyProtocol': unknown privacy protocol
```

I have tried not to specify the option at all, specify the option with blank value, specify the option with 'none' value, still no success. Any help appreciated.

**Comment by vincentbernat** [comment]
Can you provide the relevant part of your configuration?

**Reply by enkikun** [reply]
inlet.yaml:

```
metadata:
  workers: 10
  provider:
    type: snmp
    security-parameters:
      ::/0:
        user-name: user
        authentication-protocol: MD5
        authentication-passphrase: password
```
