### DISCUSSION TITLE
fix docs

### DISCUSSION THREAD

**Discussion by knpshkn** [akvorado/akvorado#87] [Q&A]
Hi,

I believe there is a typo in the docs related to the console configuration section. In [authentication](https://github.com/vincentbernat/akvorado/blob/main/console/data/docs/02-configuration.md#authentication) section there is an example:
```
authentication:
  headers:
    login: Remote-User
    name: Remote-Name
    email: Remote-Email
    logout-url: X-Logout-URL
  default-user:
    login: default
    name: Default User
```
with this example i get an error
```
Error: invalid configuration:
invalid key "Console[0].authentication"
```
according to output of `/api/v0/orchestrator/configuration/console` the correct example is:
```
auth:
  headers:
    login: Remote-User
    name: Remote-Name
    email: Remote-Email
    logout-url: X-Logout-URL
  default-user:
    login: default
    name: Default User
```
and with this changes everything works as expected
