### DISCUSSION TITLE
SNMP over IPv6 does not work from akvorado-inlet

### DISCUSSION THREAD

**Discussion by netfreak98** [akvorado/akvorado#922] [Q&A]
Not sure if it is me but for some reason  I can not get my SNMP over IPv6 working.
I already enabled IPv6 in Docker.

This is the log output I can see:
```
akvorado-inlet_1            | {"level":"error","error":"write udp [::]:60116->[fde5:5fd3:1f5:700:464c:a8ff:fec7:b570]:161: sendto: cannot assign requested address","exporter":"fde5:5fd3:1f5:700:464c:a8ff:fec7:b570","time":"2023-10-19T14:25:09Z","caller":"akvorado/inlet/metadata/provider/snmp/poller.go:114","module":"akvorado/inlet/metadata/provider/snmp","message":"unable to GET (7 OIDs)"}
akvorado-inlet_1            | {"level":"error","error":"write udp [::]:60734->[fde5:5fd3:1f5:700:2a99:3aff:fe9b:b750]:161: sendto: cannot assign requested address","exporter":"fde5:5fd3:1f5:700:2a99:3aff:fe9b:b750","time":"2023-10-19T14:25:25Z","caller":"akvorado/inlet/metadata/provider/snmp/poller.go:114","module":"akvorado/inlet/metadata/provider/snmp","message":"unable to GET (7 OIDs)"}
akvorado-inlet_1            | {"level":"error","error":"write udp [::]:50983->[fde5:5fd3:1f5:700:464c:a8ff:fec7:b570]:161: sendto: cannot assign requested address","exporter":"fde5:5fd3:1f5:700:464c:a8ff:fec7:b570","time":"2023-10-19T14:26:09Z","caller":"akvorado/inlet/metadata/provider/snmp/poller.go:114","module":"akvorado/inlet/metadata/provider/snmp","message":"unable to GET (4 OIDs)"}
akvorado-inlet_1            | {"level":"error","error":"write udp [::]:54550->[fde5:5fd3:1f5:700:464c:a8ff:fec7:b570]:161: sendto: cannot assign requested address","exporter":"fde5:5fd3:1f5:700:464c:a8ff:fec7:b570","time":"2023-10-19T14:26:09Z","caller":"akvorado/inlet/metadata/provider/snmp/poller.go:114","module":"akvorado/inlet/metadata/provider/snmp","message":"unable to GET (7 OIDs)"}
akvorado-inlet_1            | {"level":"error","error":"write udp [::]:41554->[fde5:5fd3:1f5:700:464c:a8ff:fec7:b570]:161: sendto: cannot assign requested address","exporter":"fde5:5fd3:1f5:700:464c:a8ff:fec7:b570","time":"2023-10-19T14:26:10Z","caller":"akvorado/inlet/metadata/provider/snmp/poller.go:114","module":"akvorado/inlet/metadata/provider/snmp","message":"unable to GET (4 OIDs)"}
akvorado-inlet_1            | {"level":"error","error":"write udp [::]:52796->[fde5:5fd3:1f5:700:464c:a8ff:fec7:b570]:161: sendto: cannot assign requested address","exporter":"fde5:5fd3:1f5:700:464c:a8ff:fec7:b570","time":"2023-10-19T14:26:19Z","caller":"akvorado/inlet/metadata/provider/snmp/poller.go:114","module":"akvorado/inlet/metadata/provider/snmp","message":"unable to GET (7 OIDs)"}
akvorado-inlet_1            | {"level":"error","error":"write udp [::]:38087->[fde5:5fd3:1f5:700:464c:a8ff:fec7:b570]:161: sendto: cannot assign requested address","exporter":"fde5:5fd3:1f5:700:464c:a8ff:fec7:b570","time":"2023-10-19T14:26:19Z","caller":"akvorado/inlet/metadata/provider/snmp/poller.go:114","module":"akvorado/inlet/metadata/provider/snmp","message":"unable to GET (7 OIDs)"}
akvorado-inlet_1            | {"level":"error","error":"write udp [::]:43636->[fde5:5fd3:1f5:700:464c:a8ff:fec7:b570]:161: sendto: cannot assign requested address","exporter":"fde5:5fd3:1f5:700:464c:a8ff:fec7:b570","time":"2023-10-19T14:26:20Z","caller":"akvorado/inlet/metadata/provider/snmp/poller.go:114","module":"akvorado/inlet/metadata/provider/snmp","message":"unable to GET (7 OIDs)"}
```

At the same time, manual snmpwalk commands on the host, so outside of Docker work:
```
snmpwalk --clientaddr="::" -v2c -c xxxxx udp6:[fde5:5fd3:1f5:700:464c:a8ff:fec7:b570]:161 .1
snmpwalk --clientaddr="fde5:5fd3:1f5:400:d41d:8fff:fe66:d6ad" -v2c -c xxxxx udp6:[fde5:5fd3:1f5:700:464c:a8ff:fec7:b570]:161 .1
```

My eth0 config:
```
   eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether d6:1d:8f:66:d6:ad brd ff:ff:ff:ff:ff:ff
    inet6 fde5:5fd3:1f5:400:d41d:8fff:fe66:d6ad/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::d41d:8fff:fe66:d6ad/64 scope link 
       valid_lft forever preferred_lft forever
```
Docker compose part:
```
  akvorado-inlet:
    <<: *akvorado-image
    ports:
      - 2055:2055/udp
      - 6343:6343/udp
      - 10179:10179/tcp
    restart: unless-stopped
    command: inlet http://akvorado-orchestrator:8080
    volumes:
      - akvorado-geoip:/usr/share/GeoIP:ro
      # If you prefer to use geo IP databases from host, comment the
      # above line and uncomment this one:
      # - /usr/share/GeoIP:/usr/share/GeoIP:ro
      - akvorado-run:/run/akvorado
    labels:
      - traefik.enable=true
      - traefik.http.routers.akvorado-inlet.rule=PathPrefix(`/api/v0/inlet`)
      - traefik.http.services.akvorado-inlet.loadbalancer.server.port=8080
      - akvorado.conntrack.fix=true
  akvorado-conntrack-fixer:
    <<: *akvorado-image
    cap_add:
      - NET_ADMIN
    command: conntrack-fixer
    restart: unless-stopped
    network_mode: host
    healthcheck:
      disable: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

Anyone ever had a problem like this?

**Comment by vincentbernat** [comment]
What's the output of `nsenter -t $(pgrep -f "akvorado inlet") -n ip a l`? You can also try your snmpwalk command in the context of the container this way too.

**Comment by netfreak98** [comment]
Hi,

the output is:
```
root@flowmon:/opt/akvorado# nsenter -t $(pgrep -f "akvorado inlet") -n ip a l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
474: eth0@if475: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:12:00:06 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.18.0.6/16 brd 172.18.255.255 scope global eth0
       valid_lft forever preferred_lft forever
```

Ofc this makes sense now. 
I just found a workaround by appending some lines to the compose file:

docker/docker-compose.yml:
```
networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fdef:fff:2::/64
          gateway: fdef:fff:2::1
```
```
root@flowmon:/opt/akvorado# nsenter -t $(pgrep -f "akvorado inlet") -n ip a l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
556: eth0@if557: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:13:00:03 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.19.0.3/16 brd 172.19.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fdef:fff:2::3/64 scope global nodad 
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe13:3/64 scope link 
       valid_lft forever preferred_lft forever
```
