### ISSUE TITLE
RegExp for custom dimension

### ISSUE THREAD

**Issue by SCadilhac** [akvorado/akvorado#1030]
Hello,

Thanks for the great work on this project.

It would be great to be able to derive custom dimensions from other fields (e.g. interface description) using regular expressions.
From my understanding, this sits in between two existing mechanisms:
* _Classifiers_ - Expr-based rules, executed by the ingestion code; can use RegExp, but only apply to predefined dimensions (`Connectivity`, `Provider`).
* _Custom dictionaries_ - Executed by Clickhouse upon data insertion, custom configured dimensions, but implement only CSV lookup at the moment.

What would be the right direction to go?

**Comment by vincentbernat** [comment]
@margau any advice?

**Comment by margau** [comment]
Unfortunately, I have no proper dev setup available, therefore can't have a practical look at this right now.

It seems likely possible with CustomDicts (however, CustomDicts should be renamed then, because a RegExp is no dict lookup).

I could imagine some kind of switch between e.g. "DictLookup" and "Regex" source type in https://github.com/akvorado/akvorado/blob/main/common/schema/root.go#L91 with the later doing something e.g. with https://clickhouse.com/docs/en/sql-reference/functions/string-replace-functions

**Comment by SCadilhac** [comment]
Hello @vincentbernat

What about the following?

1. Remove `custom-dictionaries` from schema, in favor of simple column definitions:

```yaml
schema:
  custom-columns:
    - name: SrcAddrIPRole
      type: String
    ....
    - name: SvcReference
      label: ServiceReference
      type: String
    - name: EPReference
      label: EndpointReference
      type: String
```

2. Declare dictionaries in the outlet (if necessary):

```yaml
core:
  custom-dictionaries:
    - name: ip-to-role
      type: lpm   # or default or cuckoo or whatever
      keys:
        - addr
      attributes:
        - role
      source: /etc/akvorado/ip_department.csv
```

3. Feed the custom columns using Expr, either per exporter, per interface (cache based on metadata) or per flow:

```yaml
core:
  interface-classifiers:
    - |
      ClassifyConnectivityRegex(Interface.Description, "^(?i)(transit|pni|ppni|ix):? ", "$1") &&
      ClassifyProviderRegex(Interface.Description, "^\\S+?\\s(\\S+)", "$1") &&
      ClassifyExternal()
    - ClassifyInternal()
    - ClassifyCustomRegex(Interface.Description, "^(.+?) - (.+)$", "$1", "SvcReference", "$2", "EPReference")
  flow-classifiers:
    - ClassifyCustomLookup("ip-to-role, [Flow.SrcAddr], ["SrcAddrIPRole"])
```
