### ISSUE TITLE
INLET kafka SASL/OAUTHBEARER saslmechanism

### ISSUE THREAD

**Issue by vincentbernat** [akvorado/akvorado#1742]
### Discussed in https://github.com/akvorado/akvorado/discussions/1714

<div type='discussions-op-text'>

<sup>Originally posted by **vseregin63** April  2, 2025</sup>
Have a good day, @vincentbernat

Where are centralized installations of ClickHouse and Kafka in our company and we want to use just Inlet and console modules without orchestrator service. In discussions https://github.com/akvorado/akvorado/discussions/58 and https://github.com/akvorado/akvorado/discussions/1685 You confirmed that we can do it. At this point we can run inlet module separately and successfully write messages to kafka with Plaintext auth method.
But we have a trouble - kafka brokers in our prod evironment supports only sasl/oauthbearer auth method. 
In such case we need to provide additionally url to get JWM token and saslmechanism must be set to OAUTHBEARER. Below example from another product 

```yaml
  kafka:
    sasl:
      user: "user"
      password: "passw"
      mechanism: OAUTHBEARER
      token-url: https://example.com/auth/realms/protocol/openid-connect/token
```

Akvorado support such sasl auth mechanism ? If NO, can we make request to add this functionality to it?

Thanks!</div>
