### ISSUE TITLE
SNMP pooler malfunction

### ISSUE THREAD

**Issue by kostik2022** [akvorado/akvorado#212]
We are trying to use v.1.6.1 (also tried 1.6.0, 1.5.7) with NetFlow as described in manual. All options regarding SNMP pooler was set.
But, looks like container even not try to make any SNMP requests (tcpdump at host external interface and at docker bridge interface shows no packets to 161 port).
Yes, metrics  shows that flows are arrived, but inlet didn't forward them to core, 'cause he didn't make SNMP resolution.
Firewall is disabled at host level, btw..

```
==== akvorado.yaml ====
inlet:
  kafka:
    compression-codec: zstd
  geoip:
    optional: true
    asn-database: /usr/share/GeoIP/GeoLite2-ASN.mmdb
    geo-database: /usr/share/GeoIP/GeoLite2-Country.mmdb
  snmp:
    workers: 4
    communities:
      ::/0: XXXXXXXXXXXXXX
    poller-timeout: 5
    poller-retries: 1
    cache-duration: 10m
    cache-refresh: 10m
    cache-check-interval: 5m
  flow:
    inputs:
      - type: udp
        decoder: netflow
        listen: 0.0.0.0:2055
        workers: 3
        receive-buffer: 10485760
  core:
    workers: 4
    exporter-classifiers:
      - ClassifySiteRegex(Exporter.Name, "^([^-]+)-", "$1")
      - ClassifyRegion("europe")
    interface-classifiers:
      - |
        ClassifyConnectivityRegex(Interface.Description, "^(?i)(transit|pni|ppni|ix):? ", "$1") &&
        ClassifyProviderRegex(Interface.Description, "^\\S+?\\s(\\S+)", "$1") &&
        ClassifyExternal()
      - ClassifyInternal()
```
