### ISSUE TITLE
Regression: sflow parsing broken in 1.7.1

### ISSUE THREAD

**Issue by knvk** [akvorado/akvorado#470]
# Bug description
After upgrading from 1.6.4 to 1.7.1 I found sflow parser is broken.
I'm not sure if it's related for all sample types, I can test only expanded one.

## Steps to reproduce the problem

**Akvorado version**: 
 ```akvorado v1.7.1
  Build date: 2023-01-27T22:03:13+0000
  Built with: go1.19.5
```
I have redacted the ip addresses below for privacy reasons. 
If you are interested (I hope) I can provide you entire .pcap dump for the flow.

The inlet itself do not report any error. Counters grow.
```
# curl -s http://localhost:8081/api/v0/inlet/metrics | grep -i sflow | grep -v '#'
akvorado_inlet_flow_decoder_count{name="sflow"} 9623
akvorado_inlet_flow_decoder_sflow_count{agent="xxx",exporter="xxx",version="5"} 9623
akvorado_inlet_flow_decoder_sflow_sample_records_sum{agent="xxx",exporter="xxx",type="ExpandedFlowSample",version="5"} 153336
akvorado_inlet_flow_decoder_sflow_sample_sum{agent="xxx",exporter="xxx",type="ExpandedFlowSample",version="5"} 38334
```

Inlet configuration:
```
inlet:
  http:
    listen: 127.0.0.1:8081
    profiler: false
  flow:
    inputs:
        - type: udp
          decoder: sflow
          listen: yyy:6000
          queuesize: 100000
          workers: 4
          receive-buffer: 16777216
          usesrcaddrforexporteraddr: true
  snmp:
      defaultcommunity: "XXX"
  kafka:
    topic: akvorado-flows
    brokers:
    - 127.0.0.1:9092
    version: 2.8.1
    flushinterval: 15s
    flushbytes: 104857599
    maxmessagebytes: 1000000
    compressioncodec: none
    queuesize: 128
  core:
    workers: 16
    defaultsamplingrate: 0
    ignoreasnfromflow: true
 ```
## Expected outcome (v1.6.4)
```
# curl  http://localhost:8081/api/v0/inlet/flows?limit=1
{
    "TimeReceived": 1676036243,
    "SequenceNum": 52461804,
    "SamplingRate": 256,
    "ExporterName": "hu-s3",
    "TimeFlowStart": 1676036243,
    "TimeFlowEnd": 1676036243,
    "Bytes": 1394,
    "Packets": 1,
    "Etype": 2048,
    "Proto": 17,
    "SrcPort": 46622,
    "DstPort": 58631,
    "OutIf": 182,
    "IPTTL": 64,
    "FragmentId": 41647,
    "FragmentOffset": 16384,
    "OutIfName": "Eth-Trunk1",
    "OutIfDescription": "hu-s3-loop-to-eth-2",
    "OutIfSpeed": 30000,
    "SrcAddr": "xxx",
    "DstAddr": "234.170.170.1",
    "ExporterAddress": "xxx",
    "InIfBoundary": "UNDEFINED",
    "OutIfBoundary": "UNDEFINED"
}
```

## Current outcome  (v1.7.1)

```
# curl  http://localhost:8081/api/v0/inlet/flows?limit=1
{
    "TimeReceived": 1676035850,
    "SamplingRate": 256,
    "ExporterAddress": "::ffff:xxx",
    "InIf": 0,
    "OutIf": 182,
    "SrcAddr": "::ffff:0.0.5.64",
    "DstAddr": "::ffff:0.0.0.17",
    "NextHop": "",
    "SrcAS": 0,
    "DstAS": 0,
    "GotASPath": false
}
```
