### ISSUE TITLE
SNMP community is always public

### ISSUE THREAD

**Issue by mirackle-spb** [akvorado/akvorado#573]
SNMP community is always "public". 

sample config:
```
---
kafka:
  compression-codec: zstd
geoip:
  optional: true
  # When running on Docker, these paths are inside the container.
  # Check docker-compose.yml for details.
  asn-database: /usr/share/GeoIP/GeoLite2-ASN.mmdb
  geo-database: /usr/share/GeoIP/GeoLite2-Country.mmdb
snmp:
  workers: 10
  communities:
    ::/0: dfsglkjaew57as4e

flow:
  inputs:
    - type: udp
      decoder: netflow
      listen: 0.0.0.0:2055
      workers: 6
      receive-buffer: 10485760
      use-src-addr-for-exporter-addr: true
    - type: udp
      decoder: sflow
      listen: 0.0.0.0:6343
      workers: 6
      receive-buffer: 10485760
      use-src-addr-for-exporter-addr: true
core:
  workers: 6
  exporter-classifiers:
    # This is an example. This should be customized depending on how
    # your exporters are named.
    - Exporter.Name startsWith "north" && ClassifySite("north")
    - Exporter.Name startsWith "south" && ClassifySite("south")
    - Exporter.Name startsWith "selectel" && ClassifySite("selectel")
#    - ClassifySiteRegex(Exporter.Name, "^([^-]+)-", "$1")
    - ClassifyRegion("spb")
    - ClassifyTenant("acme")
    - ClassifyRole("edge")
  interface-classifiers:
    # This is an example. This must be customized depending on the
    # descriptions of your interfaces. In the following, we assume
    # external interfaces are named "Transit: Cogent" Or "IX:
    # FranceIX".
    - ClassifyConnectivityRegex(Interface.Description, "^(?i)(Transit|Peering):? ", "$1") &&
      ClassifyProviderRegex(Interface.Description, "^.*: ([\\w\\d_-]+)", "$1") &&
      ClassifyExternal()
    - ClassifyInternal()
```

output from tshark:
```
Frame 20: 138 bytes on wire (1104 bits), 138 bytes captured (1104 bits) on interface enp1s0, id 0
    Interface id: 0 (enp1s0)
        Interface name: enp1s0
    Encapsulation type: Ethernet (1)
    Arrival Time: Mar 20, 2023 13:23:10.013613050 MSK
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1679307790.013613050 seconds
    [Time delta from previous captured frame: 0.003335346 seconds]
    [Time delta from previous displayed frame: 0.003335346 seconds]
    [Time since reference or first frame: 1.006754830 seconds]
    Frame Number: 20
    Frame Length: 138 bytes (1104 bits)
    Capture Length: 138 bytes (1104 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: eth:ethertype:ip:udp:snmp]
Ethernet II, Src: 02:73:d9:5b:3b:b7 (02:73:d9:5b:3b:b7), Dst: BrocadeC_de:39:15 (60:9c:9f:de:39:15)
    Destination: BrocadeC_de:39:15 (60:9c:9f:de:39:15)
        Address: BrocadeC_de:39:15 (60:9c:9f:de:39:15)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Source: 02:73:d9:5b:3b:b7 (02:73:d9:5b:3b:b7)
        Address: 02:73:d9:5b:3b:b7 (02:73:d9:5b:3b:b7)
        .... ..1. .... .... .... .... = LG bit: Locally administered address (this is NOT the factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Type: IPv4 (0x0800)
Internet Protocol Version 4, Src: 10.37.254.58, Dst: 185.97.202.21
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
        0000 00.. = Differentiated Services Codepoint: Default (0)
        .... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
    Total Length: 124
    Identification: 0x3361 (13153)
    Flags: 0x4000, Don't fragment
        0... .... .... .... = Reserved bit: Not set
        .1.. .... .... .... = Don't fragment: Set
        ..0. .... .... .... = More fragments: Not set
    Fragment offset: 0
    Time to live: 63
    Protocol: UDP (17)
    Header checksum: 0x7c39 [validation disabled]
    [Header checksum status: Unverified]
    Source: x.x.x.x
    Destination: x.x.x.x
User Datagram Protocol, Src Port: 37869, Dst Port: 161
    Source Port: 37869
    Destination Port: 161
    Length: 104
    Checksum: 0x8c50 [unverified]
    [Checksum Status: Unverified]
    [Stream index: 19]
    [Timestamps]
        [Time since first frame: 0.000000000 seconds]
        [Time since previous frame: 0.000000000 seconds]
Simple Network Management Protocol
    version: v2c (1)
    community: public
```

logs output:
```
{"level":"warn","exporter":"185.97.202.20","time":"2023-03-20T10:24:23Z","caller":"akvorado/inlet/snmp/root.go:329","module":"akvorado/inlet/snmp","message":"poller breaker open"}
{"level":"error","error":"request timeout (after 1 retries)","exporter":"185.97.202.22","time":"2023-03-20T10:24:41Z","caller":"akvorado/inlet/snmp/poller.go:186","module":"akvorado/inlet/snmp","message":"unable to GET (7 OIDs)"}
{"level":"error","error":"request timeout (after 1 retries)","exporter":"185.97.202.22","time":"2023-03-20T10:24:41Z","caller":"akvorado/inlet/snmp/poller.go:186","module":"akvorado/inlet/snmp","message":"unable to GET (4 OIDs)"}
{"level":"error","error":"request timeout (after 1 retries)","exporter":"185.97.202.22","time":"2023-03-20T10:24:41Z","caller":"akvorado/inlet/snmp/poller.go:186","module":"akvorado/inlet/snmp","message":"unable to GET (4 OIDs)"}
```

## Steps to reproduce the problem

**Akvorado version**:  1.8.1

Simple setup

## Expected outcome

Use of configured value for snmp community

## Current outcome

LookupOrDefault is always returning hardcoded default value.
