### ISSUE TITLE
`DstASPath` and `DstCommunities` no longer parsed from IPFIX/BMP since Akvorado 1.8.0

### ISSUE THREAD

**Issue by hohl** [akvorado/akvorado#672]
# Bug description

After upgrading from 1.7.2 to 1.8.4, the IPFIX inlet did suddenly no longer read in the `DstASPath` and `DstCommunities` fields from IPFIX/BMP anymore. Other fields (such as `DstAS`) are still parsed correctly. 

Testing different Akvorado version, the breaking change seems to be introduced between 1.7.2 and 1.8.0. Flow sending routers are Juniper MX with the latest recommended LTS version of JunOS (21.4R3).

Any ideas?

## Steps to reproduce the problem

**Akvorado version**: 1.8.0, 1.8.1, 1.8.2 and 1.8.3 (Docker Images)

Inlet config:

```
inlet:
  bmp:
    collectasns: true
    collectaspaths: true
    collectcommunities: true
  flow:
    inputs:
      - type: udp
        decoder: netflow
        listen: 0.0.0.0:2055
        workers: 6
        receive-buffer: 20971520 
```

All flows are generated from Juniper MX routers using IPFIX and BMP.

## Expected outcome

`DstASPath` to contain the AS path for outgoing packets. `DstCommunities` contain all BGP communities.

## Current outcome

`DstASPath` and `DstCommunities` are empty for all received flows according to Akvorado.
